### ISSUE TITLE
Securitas access broken since few days.

### ISSUE THREAD

**Issue by pganansia** [guerrerotook/securitas-direct-new-api#102]
Hi,
Since few days, I have this log messages in Home Assistant:

2023-01-25 17:19:44.711 ERROR (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] Votre demande n'a pas pu être transmise ; veuillez réessayer dans quelques minutes
2023-01-25 17:19:44.713 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/securitas/alarm_control_panel.py", line 57, in async_setup_entry
    current_state: CheckAlarmStatus = await client.update_overview(
  File "/config/custom_components/securitas/__init__.py", line 400, in update_overview
    while alarm_status.operation_status == "WAIT":
AttributeError: 'str' object has no attribute 'operation_status'

Does anyone have the same problem?
Is there a change in Securitas API access?

I have reloaded the integration. I stil have the same problem.
I have no problem to access to my alarm from the smartapp SECURITAS (Verisure in France)

Thks for your help.

**Comment by frosthal** [comment]
Same problem here...

**Comment by ToroNander** [comment]
Same here as well. Since some hours I try to figure it out.
After a HA Core update today to 2023.3 it is not working anymore.
I received the following in the log:

 Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 23:09:25 (2 occurrences)
Last logged: 23:10:00

    Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for securitas using this method at custom_components/securitas/__init__.py, line 186: hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for securitas using this method at custom_components/securitas/config_flow.py, line 173: self.hass.config_entries.async_setup_platforms(self.config, PLATFORMS)

**Comment by ToroNander** [comment]
I opened a new issue. 
Based on the fact, that [pganansia] has that issue since 2 weeks, their is no relation to HA core update from today.

**Comment by pganansia** [comment]
I apoligize because I did not update the issue.
The problem came from the alarm itself that is not able to communicate even with the App or the supervisor.
After a call to Verisure, they decided that they will change the alarm.
So for me the issue is closed.
