### ISSUE TITLE
Integration broken since HA core update to 2023.3 --> Please report issue to the custom integration author for securitas

### ISSUE THREAD

**Issue by ToroNander** [guerrerotook/securitas-direct-new-api#103]
Integration stopped working.

Log:
 Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 23:09:25 (2 occurrences)
Last logged: 23:10:00

    Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for securitas using this method at custom_components/securitas/__init__.py, line 186: hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for securitas using this method at custom_components/securitas/config_flow.py, line 173: self.hass.config_entries.async_setup_platforms(self.config, PLATFORMS)

**Comment by guerrerotook** [comment]
Let me take a look

**Comment by guerrerotook** [comment]
Solved the issue in this latest release. **https://github.com/guerrerotook/securitas-direct-new-api/releases/tag/v2.1.0.0**
