### ISSUE TITLE
Last commit breaks the Alarm Panel

### ISSUE THREAD

**Issue by SirLouen** [guerrerotook/securitas-direct-new-api#107]
I've found that the last commit [9a99864](https://github.com/guerrerotook/securitas-direct-new-api/commit/9a99864c5d0da9ca3c87d5ae57cb4995ca437300) is breaking the Alarm Panel

Some users have pointed out (#101 & #106) in the latest discussions. I'm not 100% confident but it's probably the changes in __init__.py and config_flow.py (I have not gone deep into the code though).

Just using the changes in alarm_control_panel.py helps solving the disarm issue in #97

**Comment by SirLouen** [comment]
I'm not sure the purpose of those async_forward_entry_setups

I'm reading that there was a warning in the first release of HA 2023.02 that suggested this change but it completely messes up the system.

**Comment by guerrerotook** [comment]
I'm testing this version on my setup and I will generate a new version tomorrow if everything goes well.
