### ISSUE TITLE
Integration not found

### ISSUE THREAD

**Issue by agaleraib** [guerrerotook/securitas-direct-new-api#11]
Hola,

Estoy intentando instalar la integración pero no consigo validar mi configuración, me da el siguiente error:

Integration error: securitas_direct - Integration 'securitas_direct' not found.

He copiado la carpeta "securitas_direct" dentro de "custom_components" y añadido la configuración en configuration.yaml 

La verdad no se que estoy haciendo mal.

Gracias de antemano por la ayuda.

**Comment by guerrerotook** [comment]
Asegúrate de copiar todos los ficheros del repositorio de Git en tu carpeta de Home Assistant.

**Comment by agaleraib** [comment]
Ya funciona! tuve que reiniciar HA una vez copiado el componente y antes de añadir la configuración en configuration.yaml

Por si te sirve de algo, lo que he notado también es que me daba un error de autenticación por que tenía un password creo que demasiado largo con el cual podía acceder sin problema a través de la web de Securitas direct pero no por HA. Después de cambiar el password a uno mas corto he podido acceder sin problema.

También he creado varios scripts para armar-away, armar-night y desarmar que funcionan sin problema.

Muchas gracias por tu esfuerzo compartiendo/manteniendo este componente!

**Comment by guerrerotook** [comment]
Muchas gracias por el comentario de la contraseña, porque hay otro usuario que tiene el mismo problema, se lo voy a comentar.

**Comment by bvis** [comment]
> Ya funciona! tuve que reiniciar HA una vez copiado el componente y antes de añadir la configuración en configuration.yaml
> 
> Por si te sirve de algo, lo que he notado también es que me daba un error de autenticación por que tenía un password creo que demasiado largo con el cual podía acceder sin problema a través de la web de Securitas direct pero no por HA. Después de cambiar el password a uno mas corto he podido acceder sin problema.
> 
> También he creado varios scripts para armar-away, armar-night y desarmar que funcionan sin problema.
> 
> Muchas gracias por tu esfuerzo compartiendo/manteniendo este componente!

¿Podrías compartir esos scripts? Seguro que son de utilidad para más gente. ;)
