### ISSUE TITLE
Does not update status

### ISSUE THREAD

**Issue by CJHive** [guerrerotook/securitas-direct-new-api#112]
I can only activate the alarm, but it does not reflect the alarm status.  therefore it is always raising alarm.  You don't know the alarm status.  if you restart HA, the alarm is always disabled, even if it is enabled.
![Screenshot_20230221_184032_Home Assistant](https://user-images.githubusercontent.com/42096806/220419752-737e5e55-0572-45d9-9661-94ad8e09c527.jpg)

**Comment by danise76** [comment]
Same here. Did some test and tried (just to be sure) to change the "check_alarm_panel" value.

**Comment by danise76** [comment]
This can be closed. Already treated and explained at #67

**Comment by CJHive** [comment]
Pero el problema es que se queda armando, se puede tirar así toda la vida. Ya que no sabe el estado de la alarma. Una vez que le doy a armar alarma ya no puedo hacer nada más ya que se queda esperando el estado de la alarma.

**Comment by CJHive** [comment]
![Screenshot_20230225_221227_Home Assistant](https://user-images.githubusercontent.com/42096806/221379946-f5349ca8-13cc-4dfa-8eb3-10cfca98b5ed.jpg)
![Screenshot_20230225_221141_Home Assistant](https://user-images.githubusercontent.com/42096806/221379951-b3d16442-0b26-4bd5-a8c3-7da5b0f21307.jpg)
![Screenshot_20230225_221227_Home Assistant](https://user-images.githubusercontent.com/42096806/221379957-86e05c5d-685f-4b68-8a9d-64ad76588f10.jpg)
 
4 horas más tarde sigue bloqueado en armado. Armo la alarma pero queda esperando estado aún que cada tiempo hace su consulta de estado. Pero sigue armando hace 4 horas. Asta que no reinicie HA no salta al estado de origen desarmado, estando la alarma conectado o no.

**Comment by CJHive** [comment]
![Screenshot_20230225_221121_My Verisure](https://user-images.githubusercontent.com/42096806/221380154-66fc23d9-7daa-4b0e-800d-a8c25af546f7.jpg)
![Screenshot_20230225_221141_Home Assistant](https://user-images.githubusercontent.com/42096806/221380159-8ffe6528-4cc4-4274-be25-e8062d68313b.jpg)
![Screenshot_20230225_221227_Home Assistant](https://user-images.githubusercontent.com/42096806/221380162-03fae873-bda7-4d78-9587-2b0013195f49.jpg)

4 horas más tarde sigue bloqueado en armado. Armo la alarma pero queda esperando estado aún que cada tiempo hace su consulta de estado. Pero sigue armando hace 4 horas. Asta que no reinicie HA no salta al estado de origen desarmado, estando la alarma conectado o no.

**Comment by guerrerotook** [comment]
Este problema es un poco raro de depurar. Lo que pasa es que cuando armas la alarma, le pides a la centralita que examine los dispositivos para ver que no te has dejado una ventana abierta. Este proceso puede tardar tiempo y Securitas Direct tiene como un límite para cada operación. Entonces lo que pasa es que armas la alarma, la operación de armado, que puede durar varios segundos se completa con un timeout y por eso ver que sigue armando la alarma aunque este proceso. 

Eventualmente cuando la integracion vuelva a consultar el estado de la alarma y volverá a actualizar el estado. Esto me ha pasado a mi en mi casa alguna vez, pero es algo temporal.

**Comment by CJHive** [comment]
He seguido investigando, tiene sentido lo que comentas, he estado mirando y achacaba el problema a 2 cosas o bien al usuario que uso uno secundario para HA o bien que tengo un dispositivo en anexo. Ayer llamé para sacar el dispositivo de anexo a una zona normal, y he puesto el usuario principal en HA, por ahora consigo activar la alarma sin problemas, esta tarde cambié el usuario al usuario creado para HA y activa la alarma sin problema, así que mi problema era que el sensor que esta en anexo da problemas y puede ser algo de lo que comentas. 

Ahora puedo activar la alarma con el sensor que estaba en anexo fuera de este modo. 
No puedo desactivar la alarma desde HA le doy al botón y no hace nada 
Noto que tengo puesto el código de alarma en 0000 y activa la alarma sin código, al intentar desactivar la alarma pongo los 0000 o sin código y no funciona, no desactiva

También me pasa que tengo otra alarma de una amigo en HA con usuario secundario y solo me muestra el estado no puedo ni activarla ni desactivarla presionó los botones y no hace nada.

Según he leído para quitar el código de activación de alarma es poner securitas_direct_code: NONE pero esto no me funciona
También he tenido que poner el código entre así '0000' su no me daba error 

¡Configuración no válida!
Invalid config for [securitas]: expected str for dictionary value @ data['securitas']['code']. Got 0. (See /config/configuration.yaml, line 13).

![Screenshot_20230303_190803_Home Assistant](https://user-images.githubusercontent.com/42096806/222795735-c16a2059-dc06-4049-ab87-5925a42b8a5c.png)

**Comment by CJHive** [comment]
Después de varias horas dándole y dándole, he llegado a estas conclusiones

no se por que al poner en securitas_direct_code: 0000 da error y no puedo poner un codigo, al ponerlo como '0000' se guarda el archivo y me deja reiniciar HA  
error que da 
¡Configuración no válida!
Invalid config for [securitas]: expected str for dictionary value @ data['securitas']['code']. Got 0. (See /config/configuration.yaml, line 13).

al final consegui poniendo None ( securitas_direct_code: None ) poder conectar y desconectar
entiendo que por el problema anterior no me detectava el codigo y por este motivo no me dejaba desconectar la alarma

Al conectar la alarma se queda en armando, tengo un sensor en ANEXO, despues de jugar mucho con este sensor he por fin he detectado que cuando esta activado el ANEXO se queda bloqueado en armando, supongo que recibira un mensaje HA de que se a activado la alarma mas anexo y por este motivo se queda Armando.... supongo que tengo que solicitar esta funcion. si activo la alarma con el Anexo desactivado sin problema, entiendo que recibe su mensaje normal de alarma activada y sin problemas
