### ISSUE TITLE
Undocumented settings

### ISSUE THREAD

**Issue by jeanfabrice** [guerrerotook/securitas-direct-new-api#115]
I'm struggling to make this integration at least being configured. 
Trying to setup latest 2.1.0.3, the installation doesn't match the documentation:
![image](https://user-images.githubusercontent.com/2949987/221104863-c8421b9e-3b96-4e69-bd3f-b5201dbb19cc.png)

* What is the `alarm` checkbox supposed to do?
* What `code` value should be set? Keeping the default value of 4 throw an error showing `code` is supposed to be a string. What string exactly??
![image](https://user-images.githubusercontent.com/2949987/221105392-8c380267-dbb2-4343-8d9d-b462223b386b.png)

I'm a bit lost. What am I doing wrong?
Any link to documentation would be appreciated.

**Comment by ToroNander** [comment]
Code: As u installed the Alarm together with Securitas (Hardware), u specified a code with Securitas (Code words as well). This code (digits, not characters --> string) u use for the Home panel normally. This code u have to enter here. 
User and password are not enough to access your Alarm for deactivation.

When installed, u will have a specific card in HA in which u have to enter the code to disarm. Arming is possible without this code.

Please see and post info from the log file in HA (Settings --> System --> Logs) always.
Apart HA core version would be interesting.

Did u implemented in config.yaml anything related to securitas?

BR

**Comment by guerrerotook** [comment]
You are right. Alarm doesn't do anything. Let me remove that configuration.

**Comment by jeanfabrice** [comment]
It looks like my installation was rather old (> 10y) and initially was not configured with multiple user/password (I didn't even know that existed)
I have now created a dedicated user/password for hass, and was able to setup the plugin accordingly.

Thanks both for the great help, closing.
