### ISSUE TITLE
Get "Triggered" status from the Alarm

### ISSUE THREAD

**Issue by danise76** [guerrerotook/securitas-direct-new-api#116]
Hi. 

I've been using the old integration with securitas, and had some automations based on the state change of the alarm. If i'm not work, the TRIGGERED status isn't one that appears to be in the variables. In the "old" api where this was forked, in the alarm_control_panel.py was the "STATE_ALARM_TRIGGERED" and isn't in this one.

Can the TRIGGERED stated be used? It was a good one to send alerts and turn on lights when the alarm reported it.

**Comment by JaVier-Lloret** [comment]
I also miss the TRIGERED state, I used it in case of alarm to close blinds and turn on a siren on another floor.

**Comment by guerrerotook** [comment]
That will require to call the API more often and I'm not sure about it. We don't want to upset Securitas and their API.

**Comment by danise76** [comment]
But it isn't possible to recover that status even it now be from the moment, so it can be from any moment since the last scan. It could be good to have it when you're out even you (HA) know it with delay. I could then set an script to save out the cameras footage and be sure that isn't deleted with other recording, check status of other sensors, etc.
