### ISSUE TITLE
Nothing worked till I changed DNS Servers

### ISSUE THREAD

**Issue by KoolLSL** [guerrerotook/securitas-direct-new-api#129]
After installation the integration was never starting, this in logs: "Error doing job: Task exception was never retrieved" ... "aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host customers.securitasdirect[...]"

It finally worked after I changed the DNS Servers in HA Settings / System / Network, setting IPv4 to Static and DNS Servers to 1.1.1.1. (replacing the local DNS) , and rebooting the host.

Not a bug but something to be aware. Maybe it depends of country or provider.

**Comment by guerrerotook** [comment]
That is a specific local issue that has nothing to do with the integration itself. Depending on your country, there may be a different url to connect to, but if you have trouble that is something about the PC where Home Assistant is running.
