### ISSUE TITLE
Add support for Home Assistant Comunity Store

### ISSUE THREAD

**Issue by guerrerotook** [guerrerotook/securitas-direct-new-api#13]
[Hacs ](https://hacs.xyz/)is a very popular alternative store where users can download extension. Add the necessary changes to add this component in the store.

**Comment by guerrerotook** [comment]
Added necessary files to the repo and make the PR in the hasc/default repository, https://github.com/hacs/default/pull/1185

**Comment by bvis** [comment]
I'd suggest you to create git tags to identify the versions (following [SEMVER](https://semver.org/)), and do releases in order to inform HACS you have a new version of the component.

**Comment by guerrerotook** [comment]
Yes, I need to do that for the HACS, thanks for the tip!

**Comment by guerrerotook** [comment]
Accepted in hacs
