### ISSUE TITLE
Sentinel sensors in PT

### ISSUE THREAD

**Issue by pmos69** [guerrerotook/securitas-direct-new-api#138]
Hi,

In Portugal, the API returns "SENTINEL COMFORTO" as the description of the service.
I did a quick workarround to get it working by changing:
SENTINE_CONFORT = "SENTINEL CONFORT" to
SENTINE_CONFORT = "SENTINEL COMFORTO"
in __init__.py

...but ithis is just a dirty workarround. The country should be checked and the apropriate string used.

I don't know what the apropriate place to do this check would be, so I didn't try to do it correctly and do a pull request.

**Comment by guerrerotook** [comment]
That is a very good finding, sorry, my installation is in Spanish that is where I'm testing the code. I will take a look at that.

**Comment by Borty97** [comment]
Maybe it would be great to select the country and then define variables according to this? It's easy to do?

**Comment by guerrerotook** [comment]
I already have some configuration that is dependan of the language, like the URL, so I can add this to the settings.

**Comment by Tanjohnson99** [comment]
Here in Portugal i don't have the sentinel in HA. Only 1 entity with state of the alarm.

**Comment by drk1ss** [comment]
@Tanjohnson99 make changes from the first post in /custom_components/securitas/__init__.py file, reboot. that helped to me

**Comment by Tanjohnson99** [comment]
Right! Working . Thanks.
