### ISSUE TITLE
Que exista el dispositivo Securitas Direct (o algo parecido)

### ISSUE THREAD

**Issue by alessbarb** [guerrerotook/securitas-direct-new-api#14]
Buenas de nuevo,

Al implementar esta API en Home Assistant sólo me salen las Entidades y no existe un Dispositivo que centralice todo Securitas Direct.

![image](https://user-images.githubusercontent.com/26366705/148079153-3df944ab-0392-4a25-bdaa-70107380d314.png)

![image](https://user-images.githubusercontent.com/26366705/148076800-b4a8ece0-4024-4047-b794-0392aacf374c.png)

Sería bueno que existiera el objeto Dispositivo para mejor organización en el sistema..

Entiendo que tendrá al final relación con #13. 

Mi implementación fue siguiendo esta web: https://tecnoyfoto.com/integrar-securitas-direct-a-home-assistant-y-google-home

**Comment by guerrerotook** [comment]
Estoy trabajando en esto, pero todavia no está listo! FYI.

**Comment by guerrerotook** [comment]
Hola! 

He añadido el código que crea los dispositivos para los paneles de alarma, pero parece que no están funcionando. 

https://github.com/guerrerotook/securitas-direct-new-api/blob/main/custom_components/securitas/alarm_control_panel.py#L86

Están en ese fichero, pero en mi instalación no los veo. He preguntado en el discord de los desarrolladores del Home Assistant si es que me falta algo para hacer que eso funcione. A ver que me dicen.

**Comment by guerrerotook** [comment]
Vale ya me han dicho y parece que tengo que implementar el config_flow que es la forma de añadir la integración desde la UI. Así que me pondre con eso.

**Comment by guerrerotook** [comment]
Ya está disponible la nueva versión que soporta config_flow #33 en el aparece en el listado de dispositivos y servicios.
