### ISSUE TITLE
Leer sensores magnéticos

### ISSUE THREAD

**Issue by Borty97** [guerrerotook/securitas-direct-new-api#140]
Es posible integrar los sensores magnéticos de las puertas/ventanas a tiempo real?

**Comment by bernatbm** [comment]
+1 estaría bien saberlo y las cámaras, sería posible

**Comment by petarlaf** [comment]
+1

**Comment by guerrerotook** [comment]
Nope, porque la API no está diseñada para eso. ¿Puedes hacer esa operación desde la propia app de Securtias Direct?

**Comment by NunoDMCarvalho** [comment]
> Nope, porque la API no está diseñada para eso. ¿Puedes hacer esa operación desde la propia app de Securtias Direct?

Yes. That can be done in the app. Here in Portugal we use the My Verisure app to connect to Securitas Direct.
