### ISSUE TITLE
randomically integration crash

### ISSUE THREAD

**Issue by italoc** [guerrerotook/securitas-direct-new-api#142]
Hello, i have the latest version of Home Assistant and the latest version of this integration, but randomically crash during activation or deactivation of the allarm (usually during deactivation).

when happen, i need to disable the integration, reboot HA, and reenable the integration.

there is a solution for this issue?

thanks

**Comment by guerrerotook** [comment]
Without logs or anything else it's impossible to diagnose what is the issue. Can you post some logs?
