### ISSUE TITLE
Disarm without code

### ISSUE THREAD

**Issue by montoyra** [guerrerotook/securitas-direct-new-api#149]
The disarm function from card button and inside button is different.
When you try to disarm the alarm clicking in alarm status and then disarm in the icon menu, you have to insert whatever number in the keyboard or you cannot disarm the alarm panel.
Different behaviour has the disarm button in the card. Here you can disarm without insert the code.

Always in the configuration status WITHOUT REQUIRED CODE.

Any ideas about that?

**Comment by guerrerotook** [comment]
did you setup a code in your configuration?

**Comment by montoyra** [comment]
no, i don't

**Comment by guerrerotook** [comment]
But can you explain a little bit more what is what is happening and what do you expect to happen? Thanks!

**Comment by montoyra** [comment]
Hi,

I try to explain better. With a configuration without setting a code..I expect that you never need to put code when you are going to disarm the alarm.
The disarming clicking disarm button in the card works well..I mean you don't need to put any code to disarming (obviously because of you made a configuration without code) but. with the same configuration if you go into the icon menu that show when you click in alarm status and press disarm, you have to insert whatever number in the keyboard to disarm the alarm and this doesn't make sense with no code configuration.

I expect to have explained better now.

Thanks a lot for your support
