### ISSUE TITLE
Cannot connect the alarm

### ISSUE THREAD

**Issue by agmolina19** [guerrerotook/securitas-direct-new-api#150]
Hola,

¿Hay alguna forma de forzar la conexión de la alarma cuando una de las ventanas está abierta?

Gracias!

------------------------------------------------------------------------------------

Hello,

Is there a way to force the alarm to connect when one of the windows is open?

Thank you!

**Comment by guerrerotook** [comment]
No, lo siento pero no. La API da un error de que te has dejado la ventana abierta. Es más si lo intentas con la app pasa lo mismo.
