### ISSUE TITLE
Integration with UI force me to setup a code

### ISSUE THREAD

**Issue by Jintus** [guerrerotook/securitas-direct-new-api#153]
I do not have a code associated with my alarm. We use badges to deactivate the alarm. But i can not specifies when configuring the service with UI that I have no code.

So I add a false code to pass the step but I can not deactivate with the alarm panel with and without entering the code.

How should I setup the integration for it to works ?

**Comment by geniodelmale** [comment]
Code is used by the integration when you need to unlock, it's not related to the actual alarm.

**Comment by guerrerotook** [comment]
If you setup the alarm with out a code then it will not request the code. You can also setup the integration from yaml as it says on the readme.md and not setup a code.
