### ISSUE TITLE
Tras la última actualización los sensores han dejado de funcionar.

### ISSUE THREAD

**Issue by jmatiasGH** [guerrerotook/securitas-direct-new-api#156]
Tras la última actualización de HA y con la última versión del plugin de securitas, los sensores han dejado de funcionar. Quitándolo todo y volviéndolo a poner solo sale el panel de la alarma pero no funciona, he perdido los sensores de temperatura, humedad y calidad de aire que antes salían.
- Versión de HA: Home Assistant 2023.10.3, Supervisor 2023.10.0, Operating System 11.0, Frontend 20231005.0 - latest
- Versión de Securitas v2.2.0.0

Home Assistant Core
Error unloading entry xxxxxxxx for securitas
10:23:46 – (ERROR) config_entries.py
Unable to find services.yaml for the securitas integration
10:19:19 – (ADVERTENCIA) helpers/service.py

**Comment by javiermartingonzalez** [comment]
Me ocurre lo mismo y me da un Forbidden cualquier acciók

**Comment by jmatiasGH** [comment]
Cuando empezó a fallar tuve que añadir esta configuración al configuration.yaml:
```
securitas:
  username: !secret securitas_direct_username
  password: !secret securitas_direct_password
  code: !secret securitas_direct_code
  country: ES
```
Que no estaba cuando comenzó a fallar, no recuerdo si la última vez lo quité por algo.
Para que funcione al menos el panel de la alarma lo tengo que dejar puesto, pero si reinicio el HA cada vez me dice que ha detectado una instalación de SECURITAS, aúnque ya lo haya configurado previamente.
Es como que no termina el proceso de configuración inicial y vuelve a pedirlo.

Si puedo mirar algo que ayude a ver que sucede decirme como y paso más información.

**Comment by guerrerotook** [comment]
Han cambiado la forma en la que se identificaba el sentinel. Solucionado y ahora hago una version nueva.

**Comment by jmatiasGH** [comment]
Gracias @guerrerotook por tu gran currazo con esta aplicación para HA! Ahora si puedo lo pruebo!

**Comment by jmatiasGH** [comment]
Confirmo que funciona! Solo actualizando y reiniciando ha ido bien.
