### ISSUE TITLE
2.3.0.0 update prevents state changes

### ISSUE THREAD

**Issue by zav13r** [guerrerotook/securitas-direct-new-api#160]
Hello - strange bug I experienced today.

Since updating to v 2.3.0.0 this morning, the integration reported entities as expected but no requests to change alarm status had any effect. Alarm control panel card (selecting disarm, arm etc) has no action.

There was no difference to setting alarm status by fronted, automation or service call.

Nothing was received at Securitas end, according to official app.

Nothing shows in any logs.

Reverting to v 2.2.0.0 restored the expected behaviour.

No other changes were made to config or setup.

**Comment by ToroNander** [comment]
Hi!
I observed the same, but easy to solve.
I have several automations running, activating and deactivating the alarm.
Before the update it wasn't needed to enter the 4digit code for activating, only for deactivating, now it is needed for both.

I simply added the line
code: "XXXX"
into **ALL** of the scripts which are called for the automations.

Complete part of script in yaml:

device_id: YYYXXXZZZ
domain: alarm_control_panel
entity_id: alarm_control_panel.name_of_your_installation
type: arm_home
code: "4digitcode"

With the panel the same:
Enter the code **first** and activate/decativate.

BR
Toro

**Comment by zav13r** [comment]
HI @ToroNander,

Thank you for the tip - this may work for automation/script service calls, but for the alarm panel card this doesn't work - I have wall-mounted tablets, with no option to enter a code before arm/disarm on the lovelace frontend. Same on mobile, where no option exists for entering a code before arming.

**Comment by ToroNander** [comment]
Hi!
I have also several wall-mounted tablets and when I add the Securitas Alarm to a dashboard the proposal is like in the pic below with the number block keyboard. I only know it that way, maybe because of a newer installation ?! No idea...

![HA_cardAlarm_SecDir](https://github.com/guerrerotook/securitas-direct-new-api/assets/92513002/ebb2439c-614d-4c83-9135-646fc9dcdff8)

BR
Toro

**Comment by zav13r** [comment]
I think this is linked with #162 and #163

**Comment by zav13r** [comment]
> Hi! I have also several wall-mounted tablets and when I add the Securitas Alarm to a dashboard the proposal is like in the pic below with the number block keyboard. I only know it that way, maybe because of a newer installation ?! No idea...
> 
> ![HA_cardAlarm_SecDir](https://user-images.githubusercontent.com/92513002/278468137-ebb2439c-614d-4c83-9135-646fc9dcdff8.png)
> 
> If I switch to the yaml code editor for that card and add the line 'code: "XXXX"', like above explained, it works again.
> 
> BR Toro

I don't use the standard alarm card in lovelace so don't have this by default.

**Comment by cantupaz** [comment]
@zav13r Does this work now?
