### ISSUE TITLE
"Invalid token: Expired" still on ...

### ISSUE THREAD

**Issue by bigramonk** [guerrerotook/securitas-direct-new-api#168]
I installed the new 2.4.0.2 version and could not set the alarm anymore, getting a "Invalid token: Expired" error message.
I changed the code of the __check_errros_ function in _apimanager.py_ as follows and it solved my issue:
``
if (error_item["message"] == "Invalid session. Please, try again later." or error_item["message"] == "Invalid token: Expired"):
``
I guess not all Securitas servers get updated at the same time...

**Comment by guerrerotook** [comment]
Related to #166 and a fix is on the way
