### ISSUE TITLE
Calidad del Aire: Revisión

### ISSUE THREAD

**Issue by alessbarb** [guerrerotook/securitas-direct-new-api#17]
Buenas, perdona pero el otro día no pude revisar el tema de la calidad del aire (#12).

Los valores que me salen no corresponden con los que tengo, a ver si es que lo estas considerando como un % y por eso se divide entre 100. Por ejemplo en casa tengo 200 y pico AQI, mientras que el sensor muestra sólo 2.

No salen tampoco las unidades, la calidad del aire creo que se mide como AQI (Air Quality Index).

¿Necesitas que te facilite algo?

Gracias.

**Comment by alessbarb** [comment]
Creo que ya lo he visto, en tu código tienes:

```
    def get_air_quality_data(
        self, installation: Installation, service: Service
    ) -> AirQuality:
        """Get sentinel status."""
        content = {
            "operationName": "AirQualityGraph",
            "variables": {
                "numinst": str(installation.number),
                "zone": str(service.attributes.attributes[0].value),
            },
            "query": "query AirQualityGraph($numinst: String!, $zone: String!) {\n  xSAirQ(numinst: $numinst, zone: $zone) {\n    res\n    msg\n    graphData {\n      status {\n        avg6h\n        avg6hMsg\n        avg24h\n        avg24hMsg\n        avg7d\n        avg7dMsg\n        avg4w\n        avg4wMsg\n        current\n        currentMsg\n      }\n      daysTotal\n      days {\n        id\n        value\n      }\n      hoursTotal\n      hours {\n        id\n        value\n      }\n      weeksTotal\n      weeks {\n        id\n        value\n      }\n    }\n  }\n}\n",
        }
        response = self._execute_request(content)
        result_json = json.loads(response.text)
        if "errors" in result_json:
            error_message = result_json["errors"][0]["message"]
            return error_message
        else:
            raw_data = result_json["data"]["xSAirQ"]["graphData"]["status"]
            return AirQuality(
                int(raw_data["current"]),
                raw_data["currentMsg"],
            )
```

raw_data debe coger ["data"]["xSAirQ"]["graphData"]["current"] en lugar de ["data"]["xSAirQ"]["graphData"]["status"].

**Comment by guerrerotook** [comment]
> Buenas, perdona pero el otro día no pude revisar el tema de la calidad del aire (#12).
> 
> Los valores que me salen no corresponden con los que tengo, a ver si es que lo estas considerando como un % y por eso se divide entre 100. Por ejemplo en casa tengo 200 y pico AQI, mientras que el sensor muestra sólo 2.
> 
> No salen tampoco las unidades, la calidad del aire creo que se mide como AQI (Air Quality Index).
> 
> ¿Necesitas que te facilite algo?
> 
> Gracias.

Si se está utilizando el atributo de tipo Air Quality Index, está en esta [línea](https://github.com/guerrerotook/securitas-direct-new-api/blob/main/custom_components/securitas/sensor.py#L104), Pero no he encontrado más documentación para la unidad que tengo que asignar para el tipo de calidad de aire.

https://developers.home-assistant.io/docs/core/entity/sensor/

Cómo ves la linea de AQI está vacia.

**Comment by guerrerotook** [comment]
> Creo que ya lo he visto, en tu código tienes:
> 
> ```
>     def get_air_quality_data(
>         self, installation: Installation, service: Service
>     ) -> AirQuality:
>         """Get sentinel status."""
>         content = {
>             "operationName": "AirQualityGraph",
>             "variables": {
>                 "numinst": str(installation.number),
>                 "zone": str(service.attributes.attributes[0].value),
>             },
>             "query": "query AirQualityGraph($numinst: String!, $zone: String!) {\n  xSAirQ(numinst: $numinst, zone: $zone) {\n    res\n    msg\n    graphData {\n      status {\n        avg6h\n        avg6hMsg\n        avg24h\n        avg24hMsg\n        avg7d\n        avg7dMsg\n        avg4w\n        avg4wMsg\n        current\n        currentMsg\n      }\n      daysTotal\n      days {\n        id\n        value\n      }\n      hoursTotal\n      hours {\n        id\n        value\n      }\n      weeksTotal\n      weeks {\n        id\n        value\n      }\n    }\n  }\n}\n",
>         }
>         response = self._execute_request(content)
>         result_json = json.loads(response.text)
>         if "errors" in result_json:
>             error_message = result_json["errors"][0]["message"]
>             return error_message
>         else:
>             raw_data = result_json["data"]["xSAirQ"]["graphData"]["status"]
>             return AirQuality(
>                 int(raw_data["current"]),
>                 raw_data["currentMsg"],
>             )
> ```
> 
> raw_data debe coger ["data"]["xSAirQ"]["graphData"]["Hours"] en lugar de ["data"]["xSAirQ"]["graphData"]["Hours"].
> 
> status devuelve un valor numérico que es igual a Buena, Mala, etc... Hours tiene los valores a recoger por horas.

Efectivamente, utilizo el valor current que proporciona la API que entiendo que tiene el valor actual. Ese valor es distinto del valor que te puede salir a ti en la gráfica. Me he dado cuenta de que el ultimo valor del array de hours corresponde con el ultimo valor (que no sea -9999). Puedo leer ese valor en vez de current. 

¿Qué te parece?

**Comment by alessbarb** [comment]
Entiendo que si. Si quieres lo pruebo antes de publicarlo

**Comment by Kyngo** [comment]
Siento revivir una issue muerta, pero esto sigue sucediendo. ¿Se va a actualizar la aplicación para incluir este valor corregido?

**Comment by guerrerotook** [comment]
Voy a echar un vistazo a esto y publico un fix

**Comment by guerrerotook** [comment]
Entonces para entender prefieres el valor de Buena que el número de 1.

Cómo esto:

![image](https://github.com/guerrerotook/securitas-direct-new-api/assets/769831/05270a14-80a7-4070-96cd-8607085c652f)

**Comment by guerrerotook** [comment]
I will publish a new version soon with this new change.
