### ISSUE TITLE
API test without Homeassistant ?

### ISSUE THREAD

**Issue by elfredo** [guerrerotook/securitas-direct-new-api#170]
Hi,
I would like to know if there is dummy class that I could use to try the API without the need to use HomeAssistant and the installation of a panel ?

Thanks in advance for your response.

**Comment by guerrerotook** [comment]
No there is not API test so far. I can show you how I develop the integration with another repository that I have with the home assistant source code but that's it.

**Comment by elfredo** [comment]
Yes I would be interested in this because I'm trying to use the API without HomeAssistant. I managed to do it in earlier versions, but the code has changed quite a lot.

**Comment by guerrerotook** [comment]
Hey @elfredo, @cantupaz has been working in adding support to run the integration standalone without Home Assistant. Please check the lastet version. Closing the issue.
