### ISSUE TITLE
More devices or entities found by integration

### ISSUE THREAD

**Issue by Apollon16** [guerrerotook/securitas-direct-new-api#178]
Hello,

Since yesterday, the integration no longer works in my home. I got a message telling me that the api was no longer in use. I thought it might be a problem with my HA integration. I reinstalled everything but since then no device or entity has been detected.

Do you have the same problem? Do you know what the problem is? Do you think you can solve it? 

Thanks 
![Capture d'écran 2023-12-14 111044](https://github.com/guerrerotook/securitas-direct-new-api/assets/89293183/6a6c475f-87f8-44fa-8ec7-518d441784c4)

**Comment by danise76** [comment]
Hi. 

Could you check if its similar to the #179  that i set. Can you check in the logs for the error messages from the Securitas integration?

Looks like another change in the Securitas Api, asking for a header now in the requests.

Thanks. 

Daniel


> Hello,
> 
> Since yesterday, the integration no longer works in my home. I got a message telling me that the api was no longer in use. I thought it might be a problem with my HA integration. I reinstalled everything but since then no device or entity has been detected.
> 
> Do you have the same problem? Do you know what the problem is? Do you think you can solve it?
> 
> Thanks ![Capture d'écran 2023-12-14 111044](https://private-user-images.githubusercontent.com/89293183/290484114-6a6c475f-87f8-44fa-8ec7-518d441784c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NDk3MjQsIm5iZiI6MTcwMjU0OTQyNCwicGF0aCI6Ii84OTI5MzE4My8yOTA0ODQxMTQtNmE2YzQ3NWYtODdmOC00NGZhLThlYzctNTE4ZDQ0MTc4NGM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDEwMjM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmOGYxNTA4YTQ1MjhhMGIxMDQ3MDY2MDVmOWZmNjFmMDk0MTI2MDI2MTZmMmY3NTE4MDE5ODI1OGVhZTc0NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5cfREcca3LJiTLwANBzrZkigra6zyY1K5fqIWSU7WbM)

**Comment by Apollon16** [comment]
Hello,

I can confirm that we have the same problem.

`Error while setting up securitas platform for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/securitas/alarm_control_panel.py", line 61, in async_setup_entry
    current_state: CheckAlarmStatus = await client.update_overview(
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/securitas/__init__.py", line 397, in update_overview
    status.status,
    ^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'status'
`
