### ISSUE TITLE
services.yaml

### ISSUE THREAD

**Issue by pganansia** [guerrerotook/securitas-direct-new-api#180]
Hi,
Thank for the good and very useful work you did. it works fine.
I have a little request : We probably have all this warning at Hommeassistant boot

Logger: homeassistant.helpers.service
Source: helpers/service.py:548
First occurred: 13:50:13 (3 occurrences)
Last logged: 13:50:13

Unable to find services.yaml for the securitas integration

Is it possible to create a dumb services.yaml file so that the warnin will end to raise up?
Rgds.

**Comment by jojo01fr** [comment]
You just need to create an empty file services.yaml in

**Comment by pganansia** [comment]
Thanks it works.
