### ISSUE TITLE
Separate the Securitas API manager from the HA integration

### ISSUE THREAD

**Issue by cantupaz** [guerrerotook/securitas-direct-new-api#184]
First, thanks @guerrerotook for all your work in this integration. Being able to use HA instead of the official app makes me extremely happy. Second, I'm probably 80% done on what I'm proposing to do here, so I'm not trying to add a lot of work. Let's discuss.

What: I'm proposing to separate the HA integration from the internal dealings of Securitas' API, so all the API logic is encapsulated and abstracted into its own, instead of having little bits of API logic in HA.

Why: As a customer of Securitas, I'd like to be able to send commands directly to my alarm system without having to use HA. And, as a user of HA, I'd like to debug the integration without having to worry about API details. This is a common pattern in many HA integrations, probably because it helps speed up testing.

What does "done" mean?
* HA integration continues to work (obviously :-))
* We can run simple scripts outside of HA to send commands to Securitas
* The API deals with errors by throwing exceptions

"Done" does not mean...
* Separating the HA integration and API repositories. This may be a good idea later.

If someone wants to see WIP and give suggestions:
https://github.com/cantupaz/securitas-direct-new-api/tree/exceptions

**Comment by guerrerotook** [comment]
Hey, thanks very much for the suggestion. Of course we can do that. How would you like to do those changes? I can give you contributions access to the repository if you want, so you can work on those changes? 

Thoughts?

**Comment by cantupaz** [comment]
Thanks. I was thinking about sending you pull requests, so you can review things and incorporate them as you see fit. But contribution access would also work. Whatever you prefer.

In any case, I'd recommend that you integrate the open PR first, so there are not many changes coming in at once, and that PR also has a few small bug fixes.

Feliz Navidad.

**Comment by cantupaz** [comment]
I'm almost done with this, but I'd like to test it for a few days in my system. 


I also noticed that the API changed in the past couple of days. Now you need to add 
 'auth': '{"loginTimestamp": 1704209695413 ....}
and for many operations also add X-capabilities to headers:
            headers["X-Capabilities"] = installation.capabilities


See https://github.com/cantupaz/securitas-direct-new-api/blob/exceptions/custom_components/securitas/securitas_direct_new_api/apimanager.py

**Comment by elfredo** [comment]
Hi and Feliz Año Nuevo!
Is it now possible to use the API without HA integration ?
Thank you !

**Comment by cantupaz** [comment]
It is not a separate package that you could install on its own, but the files in securitas_direct_new_api are an API wrapper that you can use without HA. For example, see the file basic_operations.py in the examples folder. Separating into its own repository makes sense, but for now you'd have to clone the whole repo and ignore the HA part.
