### ISSUE TITLE
[BUG] It refresh every minute while 5 minutes refresh period is set

### ISSUE THREAD

**Issue by sh4rks** [guerrerotook/securitas-direct-new-api#185]
Hi @guerrerotook !

Thanks for your work!

since the latest version, the integration refresh the alarm state every minute while I have set 5 minutes refresh period on the configuration.

Thanks!
![IMG_9798](https://github.com/guerrerotook/securitas-direct-new-api/assets/3998380/18cea45d-bdfa-4c23-9a5e-0116fe10c7a5)

**Comment by guerrerotook** [comment]
There is a new option in the integration so you can set up what frequency the integration call the server.

**Comment by sh4rks** [comment]
> There is a new option in the integration so you can set up what frequency the integration call the server.

Already set to 5 minutes but it seems to not be taken into account by the integration.

![IMG_9799](https://github.com/guerrerotook/securitas-direct-new-api/assets/3998380/10398e70-fef5-4be7-b4c7-3421b5b7ba16)

**Comment by Fluimucil** [comment]
Same problem here. I tried to change the scan intervale but it keeps scanning every minute. I had to disable the integration as Securitas keeps calling because of the number of requests

**Comment by sh4rks** [comment]
> Same problem here. I tried to change the scan intervale but it keeps scanning every minute. I had to disable the integration as Securitas keeps calling because of the number of requests

I downgrade to 2.4.0.4 and it’s working fine.

**Comment by miquellaboria** [comment]
Same problem here, if you check “Check the Status of the panel…” it refresh every minute and don’t use Scan Interval.

Thanks for the help!

**Comment by sh4rks** [comment]
@guerrerotook : I saw the PR closed. I downloaded the version in the main branch, it seems not fixed.

![IMG_0038](https://github.com/guerrerotook/securitas-direct-new-api/assets/3998380/6db31087-46e5-4bec-9ce2-5566b04c7cf6)

**Comment by guerrerotook** [comment]
What happening right there is the option Check the Status of the panel that you may have checked. This force to check the alarm panel every time, please take a look at the readme.md file to understand what it does.

https://github.com/guerrerotook/securitas-direct-new-api?tab=readme-ov-file#features

By the way this is not a bug.

**Comment by sh4rks** [comment]
@guerrerotook :

so what should I do? 
I disarm alarm when I enter/exit home through the panel so I need to check the panel but refresh every minutes the panel state cause the integration to stop at a moment as you can see below.
maybe you can implement an interval to refresh the panel as you have done for the server?

Thanks you.
![IMG_0041](https://github.com/guerrerotook/securitas-direct-new-api/assets/3998380/fd566c34-30a6-4203-b9bd-54fbca28d14e)
