### ISSUE TITLE
Status not updating anymore. Bad confit or something else?

### ISSUE THREAD

**Issue by PozoSer** [guerrerotook/securitas-direct-new-api#187]
I'm having an issue where the status does not get updated unless I manually reload the integration. 

It has started recently (can't remember the exact date but a month ago it worked fine). 

Securitas did give me a call to tell me that I was making too many requests to the alarm system, so I went ahead and changed the config as:

Scan interval:600 (are these seconds or min)?

Unchecked the "check status of the panel in every request"

The delay before arming and disarming is still set to 10.

Any help would be really appreciated as I change the heating parameters using the alarm status.

Thanks for all the work.

**Comment by RenZan** [comment]
@PozoSer these are seconds for the interval.

And the main issue is about this issue I think:  https://github.com/guerrerotook/securitas-direct-new-api/issues/179

**Comment by guerrerotook** [comment]
Yes, that is the case, closing this issue. Thanks for the reply.
