### ISSUE TITLE
Integración con Securitas Direct MoonShot

### ISSUE THREAD

**Issue by jjavin** [guerrerotook/securitas-direct-new-api#190]
Hola!

En primer lugar, agradecer vuestra dedicación, es una auténtica pasada poder integrar la alarma de Securitas en Home Assistant.

Hace unos días me cambiaron la alarma FAST por la nueva Moonshot, y a partir de ahí empezaron mis problemas con la integración. Aparentemente, conecta correctamente, me indica cuando está desconectada y cuando está conectada. El problema viene cuando intento conectarla o desconectarla desde Home Assistant. En el mando (que tiene 3 botones) uno es para conectar el modo TOTAL (que conecta tanto interior como exterior todos los elementos), después hay que parcial (que conecta los perimetrales exteriores y los magnéticos de puertas y ventanas) y el tercero que es desconexión, que desconecta todo.

Normalmente, uso el segundo botón, que conecta exterior y perimetrales, en Home Assistant me sale como "Armada Personalizada" 

Cuando en Home Assistant le doy después a armar personalizada, (el último botón) solo me arma los perimetrales del exterior. Si intento desarmarla no me hace nada.

Sin embargo, si la conecto desde el mando, en el botón que me conecta exterior + magnéticos y después le doy a desconectar desde Home Assistant me desconecta los magnéticos pero nunca el modo exterior. 

Os dejo unas capturas de cómo se conecta desde la APP:

![IMG_2690](https://github.com/guerrerotook/securitas-direct-new-api/assets/134804033/7ee5bf3e-1c19-4894-830d-76585df2e7f2)

Al darle a "Otros modos"
![IMG_2692](https://github.com/guerrerotook/securitas-direct-new-api/assets/134804033/7217d1a3-1e79-4196-8016-a92b79345e01)

Espero que podais ayudarme. 

Muchas gracias!

**Comment by guerrerotook** [comment]
Hola @jjavin lo del tema de la alarma de perímetro es una opción que todavia no se soporta de todo porque hay gente que si la tiene y gento que no. Por eso te sale esa opción de personalizada. Voy a ver si hago una opción para que puedas especificar que tienes una alarma de perímetro para que de forma predeterminada te arme y desarme esta opción.

**Comment by guerrerotook** [comment]
He creado una nueva issue para trabajar en añadir esa funcionalidad #193, cierro esta.

**Comment by jjavin** [comment]
Muchas gracias @guerrerotook, si necesitas alguna información adicional aquí estoy!

Un saludo,
