### ISSUE TITLE
Adds support for PERI alarms

### ISSUE THREAD

**Issue by guerrerotook** [guerrerotook/securitas-direct-new-api#193]
There are some users out there that they have this perimeter option enabled for their alarms. So when they arm and disarm, they have to send ARM1PERI1 instead of ARM1, for disarming is the same, DARM1DARMPERI instead of DARM1.

This issue is for adding a new configuration option in the config_flow for Perimeter support and also in the new update options that you can do after you have the component added to Home Assistant.

**Comment by cantupaz** [comment]
I'm working on this. I hope to send a PR soon.

**Comment by cantupaz** [comment]
should fix this issue: https://github.com/guerrerotook/securitas-direct-new-api/issues/7

**Comment by jjavin** [comment]
Hello

For your help, the code to disarm partial interior and perimetrals is: DARM1DARMPERI and to arm partial interior + perimetrals: ARMDAY1PERI1

Thank you!

**Comment by cantupaz** [comment]
> Hello
> 
> For your help, the code to disarm partial interior and perimetrals is: DARM1DARMPERI and to arm partial interior + perimetrals: ARMDAY1PERI1
> 
> Thank you!

Very useful. Thanks. 

In the HA world of alarm modes as Home, Away, Night, Custom. I think this should be "Night" right? (Besides, the current command for Night mode doesn't work in my system: Request ARMNIGHT1 is not valid for Central Unit)
