### ISSUE TITLE
Can't initiate the integration

### ISSUE THREAD

**Issue by Bbqdoc** [guerrerotook/securitas-direct-new-api#196]
Hi, when I try to configure it in configuration.yaml I obtain and error message:
Invalid config for 'securitas' at configuration.yaml, line 298: expected str for dictionary value 'securitas->username', got 12345678
My login is a number, (of course is not 12345678 but the number of my identity document).
Is there any problem because of the format of my login or it is a mistake from a noob? I am from Spain and it's the login that I have. Thx

**Comment by guerrerotook** [comment]
Put your username in double quote like this "1234567890"

**Comment by Bbqdoc** [comment]
OMG what a noob mistake. Solved. Thank you so much
