### ISSUE TITLE
Add CL as domain in domains.py

### ISSUE THREAD

**Issue by Zuirdj** [guerrerotook/securitas-direct-new-api#200]
Hi

I'm Verisure client in Chile, and tried to check if securitas-direct integration was working for my country. It showed error each time I tried to add it as integration, using CL as country code . Checking the logs, it was directing to securitasdirect.cl, and in Chile we use verisure.cl.

May you add the following line in domains.py ?

`"cl": "https://customers.verisure.cl/owa-api/graphql",
`
I manually added the domain in the file and the integration is now working, using 2FA. It is only showing the panel as entity, and not the sensors.
![securitas_CL](https://github.com/guerrerotook/securitas-direct-new-api/assets/157620474/cf013368-d45c-4eae-a09e-4476ac0e68d6)
![image](https://github.com/guerrerotook/securitas-direct-new-api/assets/157620474/61ee653d-c753-43a8-9d96-e31d94109729)

Thank you

**Comment by cantupaz** [comment]
thanks for sending the URL for Chile. 

Support for this should go out in the next release. If you want to test, you can install from my repo: https://github.com/cantupaz/securitas-direct-new-api

HACS->Integrations->Custom repositories (from the "..." menu in the top right)

**Comment by cantupaz** [comment]
The latest release (2.7.1) should have fixed this

**Comment by cantupaz** [comment]
The latest release (2.7.1) should have fixed this
