### ISSUE TITLE
activate the perimetral status with the integration

### ISSUE THREAD

**Issue by mattiabrunello5** [guerrerotook/securitas-direct-new-api#201]
hi 
i try with **personalized** but activate only the **perimetral** 

i try with in **home** but activarte the **partial**

i need to activate the **perimetral and the partial at the same time** 

thanks for future answer 

bye

**Comment by cantupaz** [comment]
When you did the initial installation, did you select the checkbox that says "Is there a perimetral alarm?" 
If you did and it doesn't work, can you send logs, please?

**Comment by cantupaz** [comment]
actually, I think I know what the problem is. Will fix in the next release.

**Comment by cantupaz** [comment]
The latest release (2.7.1) should have fixed this
