### ISSUE TITLE
Error when arming and disarming

### ISSUE THREAD

**Issue by M1gul1t0** [guerrerotook/securitas-direct-new-api#205]
Hello, I have updated the integration to the latest version, when I try to arm or disarm the integration from homeassistant an error occurs.

The alarm_control_panel/alarm_disarm service could not be called. 'ApiManager' object has no attribute 'protom_response'

Does anybody know what is it due to?

sorry for my english but i don't know how to speak it

**Comment by TheGui01** [comment]
Hello,

I have the same issue here with v2.7.1.
I had to delete the app to be able to rollback propoerly on 2.7

Rgds,
Guillaume

**Comment by cantupaz** [comment]
I found a bug that may be the cause of this, but to be sure: Does this happen all the time?

**Comment by Nodezero1** [comment]
Hello, For me I was having the same response every time I tried to arm the alarm and rolled back to the previous version.  Just to add, I am using Verisure France.

**Comment by Osconse** [comment]
I have the same problem and error since the last update.

**Comment by rencmbr** [comment]
Same problem since the update to version 2.7.1.0. 
I am using Verisure Brazil.

**Comment by petarlaf** [comment]
Same issue since last release. Both for arming and disarming.

"HomeAssistantError: 'ApiManager' object has no attribute 'protom_response'"

**Comment by garybrowngeo** [comment]
Same issue. Reverted to previous version (2.7.0.0) and problem no longer occurs.

**Comment by samatild** [comment]
+1 
rolled back to 2.7.0.0 and the issue is gone

**Comment by cantupaz** [comment]
Closing. Fixed in 2.7.2. please reopen if needed.
