### ISSUE TITLE
Error API since frebrery 12

### ISSUE THREAD

**Issue by JaVier-Lloret** [guerrerotook/securitas-direct-new-api#208]
Since February 12, the application has given me an error when requesting a change.  the error: API manager object has not attribute protom_response.

Is it my problem or has something changed in securitas direct?

Thanks for your time.

**Comment by pauljwhelan** [comment]
I'm getting the same error. I'm not 100% sure but I think it might have started when I upgraded to 2024.2.2 I'll try and backout that upgrade when i get some time

**Comment by rencmbr** [comment]
Probably this error is the same of #205 , and was introduced in version 2.7.1. 0 . Downgrading to version 2.7.0.0 is the current solution to it.

**Comment by JaVier-Lloret** [comment]
I use 2024.1.3 and hace the problem. Isn't the HA version.  I thing is a problem with securitas direct API.Enviado desde mi Galaxy
-------- Mensaje original --------De: pauljwhelan ***@***.***> Fecha: 19/2/24  23:42  (GMT+01:00) Para: guerrerotook/securitas-direct-new-api ***@***.***> Cc: JaVier-Lloret ***@***.***>, Author ***@***.***> Asunto: Re: [guerrerotook/securitas-direct-new-api] Error API since frebrery 12 (Issue #208) 
I'm getting the same error. I'm not 100% sure but I think it might have started when I upgraded to 2024.2.2 I'll try and backout that upgrade when i get some time

**Comment by pauljwhelan** [comment]
Thanks for the heads up. I'll go back to 2.7.0.0

**Comment by pauljwhelan** [comment]
Working again for me after downgrading. Thanks.
