### ISSUE TITLE
Add Ireland (IE)

### ISSUE THREAD

**Issue by oriold** [guerrerotook/securitas-direct-new-api#210]
Add Ireland:

`IE: https://customers.verisure.ie/owa-api/graphql"`

And English language for Ireland:

"IE": "en"

Thanks in advance.

**Comment by gilbertorconde** [comment]
in the code there's a default template for domains that looks like this: `https://customers.securitasdirect.{country}/owa-api/graphql` and a default lang as en. i believe if you set the Country Code to "ie" in the login panel everything would work just fine for you.

**Comment by oriold** [comment]
Looks like the file is:

[securitas-direct-new-api](https://github.com/guerrerotook/securitas-direct-new-api/tree/main)/[custom_components](https://github.com/guerrerotook/securitas-direct-new-api/tree/main/custom_components)/[securitas](https://github.com/guerrerotook/securitas-direct-new-api/tree/main/custom_components/securitas)/[securitas_direct_new_api](https://github.com/guerrerotook/securitas-direct-new-api/tree/main/custom_components/securitas/securitas_direct_new_api)
/domains.py

In Ireland we use verisure. Can you change it? I maybe can do a PR as well

**Comment by cantupaz** [comment]
I'm testing the change. Hold on :-)

**Comment by gilbertorconde** [comment]
> Looks like the file is:
> 
> [securitas-direct-new-api](https://github.com/guerrerotook/securitas-direct-new-api/tree/main)/[custom_components](https://github.com/guerrerotook/securitas-direct-new-api/tree/main/custom_components)/[securitas](https://github.com/guerrerotook/securitas-direct-new-api/tree/main/custom_components/securitas)/[securitas_direct_new_api](https://github.com/guerrerotook/securitas-direct-new-api/tree/main/custom_components/securitas/securitas_direct_new_api) /domains.py
> 
> In Ireland we use verisure. Can you change it? I maybe can do a PR as well

You're right, i miss that
