### ISSUE TITLE
LLamada de Securitas por número de peticiones de consulta

### ISSUE THREAD

**Issue by jmatiasGH** [guerrerotook/securitas-direct-new-api#218]
Con la última versión instalada, me han llamado los de Securitas dos ocasiones en un día para pedirme si puedo desconectar la aplicación que hace peticiones cada 25 segundos, que eso puede provocar que se bloquee la alarma, y que si puedo lo desconecte o que haga peticiones cada menos tiempo. ¿Hay forma de cambiar el número de peticiones cada x tiempo que hace la integración?

**Comment by jjavin** [comment]
A mi también me llamaron y les dije que en ningún momento indicaban que había un numero máximo de consultas y me dijo que tranquilo que no me volvían a molestar mas. Eso si me he fijado que en la app oficial en "Actividad" me da un error "The System is temporaly unavailable" no se si es un problema de ellos o que estan capando a los que superan X peticiones.

**Comment by cantupaz** [comment]
Parece ser culpa de un cambio que introduje en enero. Acabo de crear un pull request para arreglarlo.

**Comment by jjavin** [comment]
Por si os sirve de ayuda, a mi me dijeron en atención al cliente que tienen un problema con sus servidores. Yo no consigo ver en la APP oficial la "Actividad" de la alarma me da error "Error 502 gateway timeout", llevo así 2 semanas y parece que no les urge arreglarlo... :\

Un saludo y gracias
