### ISSUE TITLE
Setup of platform securitas is taking longer than 60 seconds. Startup will proceed without waiting any longer.

### ISSUE THREAD

**Issue by alessbarb** [guerrerotook/securitas-direct-new-api#22]
Buenas, me salen algunos errores en Home Assistant, este es uno de ellos:

```
Logger: homeassistant.components.alarm_control_panel
Source: helpers/entity_platform.py:297
Integration: Panel de control de alarmas (documentation, issues)
First occurred: 19:22:03 (1 occurrences)
Last logged: 19:22:03

Setup of platform securitas is taking longer than 60 seconds. Startup will proceed without waiting any longer.
```

**Comment by alessbarb** [comment]
Entiendo que esta relacionada con la issue #23

**Comment by guerrerotook** [comment]
Hola, ese mensaje sale porque Home Asistant espera a que todas las integraciones este inicializadas antes de enviar un evento notificando que el sistema está listo. Como en el caso de la alarma esto depende de lo que tarde securtas direct, este proceso, se puede demorar tiempo y es por eso que aparece ese mensaje. Puedes ignorar ese mensaje porque el sistema eventualmente se inicializará y funcionará sin problemas.
