### ISSUE TITLE
Night arm is not working

### ISSUE THREAD

**Issue by hajar97** [guerrerotook/securitas-direct-new-api#221]
Is it by design that Night arming is not working? 

I would like to create an automation that after certain hour in the evening a Night arming would turn on. Currently I have to manually do that through My Securitas app or web and Night arming in HA doesn't do anything. Can this be fixed somehow?

**Comment by cantupaz** [comment]
I use night mode almost daily, so it's supposed to work.

Do all the other modes work well?

Do you have an alarm with sensors outside your home (perimetral or exterior)?

**Comment by guerrerotook** [comment]
Do you have any kind of log?

**Comment by hajar97** [comment]
I was just trying to get the long and found out that I cannot connect to Securitas from my home network anymore, neither via web nor via mobile phone app My Verisure. Connecting via 4G works perfectly.

Could it be that my IP addressed got banned by Verisure because Home Assistant app was polling the API too much and they blocked it?

**Comment by guerrerotook** [comment]
Hey @hajar97, what is happening is that what was reported before. 

https://github.com/guerrerotook/securitas-direct-new-api/issues/230#issuecomment-2099482334

The problem is that when you make that amount to request to their API they kindly ban your IP for a period but if you keep making request then you are expanding your ban. 

So what I did from my side was to increase the amount of time my alarm updates to an hour.

**Comment by hajar97** [comment]
Why let people get banned and then manually update this parameter when they discover the issue. Why not set this to be the default update frequency in the plugin so nobody gets banned?On 16 May 2024, at 14:38, Luis Guerrero ***@***.***> wrote:﻿
Hey @hajar97, what is happening is that what was reported before.
#230 (comment)
The problem is that when you make that amount to request to their API they kindly ban your IP for a period but if you keep making request then you are expanding your ban.
So what I did from my side was to increase the amount of time my alarm updates to an hour.
