### ISSUE TITLE
Gets stuck in arming mode

### ISSUE THREAD

**Issue by pmcastro10** [guerrerotook/securitas-direct-new-api#223]
It get stuck in arming mode and no more. And the worst thing is that my android app stopped working too….

**Comment by cantupaz** [comment]
Perhaps your account is locked for some reason? Try to make the official app work first and only when it works try the HA integration.

**Comment by pmcastro10** [comment]
Indeed. It seems that the installation of the API coincided with the breakage of the alarm control unit. They changed the control unit and everything now works fine. Thanks and regards.

Efectivamente. Parece que coincidió la instalación de la api con la rotura de la centralita de la alarma. Me han cambiado la centralita y ya funciona todo bien. Gracias y saludos.

**Comment by cantupaz** [comment]
Que bueno que ahora funciona. Saludos.
