### ISSUE TITLE
Cant login

### ISSUE THREAD

**Issue by TryhomeIT** [guerrerotook/securitas-direct-new-api#228]
Hi, I get unknow error everytime i try to configure. Password and username are correct.
For Portugal what country code i need to use?
This installation is on an docker home assistant.

**Comment by lenny005** [comment]
Same issue !

**Comment by cantupaz** [comment]
For Portugal use PT. Try your username and password in the official app (log out and then try logging in). Sometimes Securitas blocks accounts and you need to go through their "lost password" steps.

**Comment by guerrerotook** [comment]
Do you have any kind of logs or error that show up in your home assistant?

**Comment by lenny005** [comment]
Indeed it was an issue with my account on Verisure, changed the password and now it is ok ! thanks a lot and sorry for this
