### ISSUE TITLE
Setup of alarm_control_panel platform securitas is taking over 10 seconds.

### ISSUE THREAD

**Issue by alessbarb** [guerrerotook/securitas-direct-new-api#23]
Buenas, me salen algunos errores en Home Assistant, este es uno de ellos:

```
Logger: homeassistant.components.alarm_control_panel
Source: /usr/local/lib/python3.9/asyncio/events.py:80
Integration: Panel de control de alarmas (documentation, issues)
First occurred: 19:21:13 (1 occurrences)
Last logged: 19:21:13

Setup of alarm_control_panel platform securitas is taking over 10 seconds.
```

**Comment by alessbarb** [comment]
Entiendo que esta relacionada con la issue #22

**Comment by guerrerotook** [comment]
Te pego la misma respuesta:

Hola, ese mensaje sale porque Home Asistant espera a que todas las integraciones este inicializadas antes de enviar un evento notificando que el sistema está listo. Como en el caso de la alarma esto depende de lo que tarde securtas direct, este proceso, se puede demorar tiempo y es por eso que aparece ese mensaje. Puedes ignorar ese mensaje porque el sistema eventualmente se inicializará y funcionará sin problemas.
