### ISSUE TITLE
Widget not responding on Android Auto

### ISSUE THREAD

**Issue by opack** [guerrerotook/securitas-direct-new-api#238]
Hi!

I live in France and this plugin is the only way I can arm/disarm my Verisure alarm using HA, so many thanks for that! 🙏

Unfortunately, the widget is unresponsive on Android Auto. It would be wonderful to be able to arm/disarm my alarm from the screen of my car, without the need to reach for my phone! 🤩 

Is it some kind of limitation? Is it an issue that is planned to be resolved? Or maybe it is a planned future feature?

Thanks again for your work on this plugin 🙏

**Comment by KoolLSL** [comment]
It is possible from AndroidAuto by calling scripts which arms/disarms the alarm. So it's an extra step compared to widget but the scripts can also do other things like switching lights.

**Comment by opack** [comment]
Thanks for the answer! I had the same idea just a bit before you answer and did that, and it works like a charm ;-)
