### ISSUE TITLE
Intregration dosen't work (IT Verisure)

### ISSUE THREAD

**Issue by gabrynofear** [guerrerotook/securitas-direct-new-api#249]
Integration is not working. It only checks the alarm status but does not enable or disable the alarm. The only enabling that works is perimeter arming.
I attach the error log.
Thanks in anticpo for the support.

Registratore: custom_components.securitas
Fonte: custom_components/securitas/__init__.py:420
Integrazione: Securitas Direct (documentazione, problemi)
Prima occorrenza: 03:51:25 (83 occorrenze)
Ultima registrazione: 18:33:24

('alarm-manager.alarm_process_error', {'errors': [{'message': 'alarm-manager.alarm_process_error', 'name': 'ApiError', 'time_thrown': '2024-09-01T15:57:30.189Z', 'data': {'res': 'ERROR', 'err': '10', 'status': 500}, 'path': ['xSCheckAlarm']}], 'data': {'xSCheckAlarm': None}}, {'app': '{"appVersion": "10.102.0", "origin": "native"}', 'User-Agent': 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.124 Safari/537.36 Edg/102.0.1245.41', 'X-APOLLO-OPERATION-ID': '64c0ffaed5f21fd45b2c67b113a8a1e86e33e94adc119e92a2018ede10913fd676302541ee1f2493fc6dfdda507e177b0008f957252e0a4b3be708ab41220fa9', 'X-APOLLO-OPERATION-NAME': 'CheckAlarm', 'extension': '{"mode":"full"}', 'numinst': '2331058', 'panel': 'SDVFAST', 'X-Capabilities': 'eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIyMGYxZDFmZi1mNTZhLTRkMmUtYTEyNS0xODk3ZjEyNGU1ODAiLCJpYXQiOjE3MjUyMDU4ODMsImV4cCI6MTcyNTIwNjc4Miwicm9sZSI6Ik9XTkVSIiwiaW5zIjoiMjMzMTA1OCIsImNhcCI6WyJFU1RJTlYiLCJBUk1EQVkiLCJBUk1OSUdIVCIsIlBFUkkiLCJBUk0iLCJESVkiLCJHQyIsIkFTSSIsIkVTVCIsIlVOUFJPVEVDVCIsIkRBUk0iLCJJTlMiLCJJTUciLCJOT1QiLCJBQ1QiLCJDT05GIiwiUkVGRVJSQUxQUk9HUkFNIiwiRFlOQU1JQ0lORk8iLCJPTFMiLCJTRUNPTkRJTlNUQUxMQUQiLCJTTUFSVE5PVCIsIktFWSIsIkNBTUVSQVMiLCJQTEFOIiwiTVlTRCIsIlBBTkVMQ09ORiIsIlNDSCIsIkJJTExTIiwiSU5TVFdPUkRTIiwiQ09ORlNFUlYiLCJQQVlNRU5URyIsIldIQVRORVciLCJDT05UTUdSRkFRIiwiQ09OVE1HUkRPV04iLCJDT05UTUdSTVlTRVJWIiwiV0hBVFNBUFAiLCJVUERDVUVORVhUSU1FIiwiVElNRUxJTkUiLCJOT1RDT05GIiwiREVWSUNFU0NPTkYiLCJSRU1JTkRFUlMiLCJJTkFQUENBTVBBSUdOIiwiQVJNSU5URlBBUlQiLCJBUk1QQVJURklOVCIsIkRFQUNUSVZBVEVaT05FIl19.0Eeb8z3325DwAgUjNPwzve6lxKIRrxboOd3gOHCX1vw', 'auth': '{"loginTimestamp": 1725205882749, "user": "01381380565", "id": "OWA_______________01381380565_______________2024911757793927", "country": "IT", "lang": "it", "callby": "OWA_10", "hash": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMTM4MTM4MDU2NSIsImNudCI6IklUIiwiY2J5IjoiT1dBXzEwIiwidmVyIjoiMTAuMTAyLjAiLCJ1c3JpZCI6IjM0MzI2MjIiLCJqdGkiOiIzNzU5OWNkMy1kOWNkLTQ5ODUtOWVlZi1jYTNmZWQwOGU3YjMiLCJpYXQiOjE3MjUyMDU4ODIsImV4cCI6MTcyNTIwNjc4Mn0.HAeFtLbNJqsTWj1J8dwxnUIWfwtLGXtTsNABSsW_XQU"}'}, {'operationName': 'CheckAlarm', 'variables': {'numinst': '2331058', 'panel': 'SDVFAST'}, 'query': 'query CheckAlarm($numinst: String!, $panel: String!) {\n xSCheckAlarm(numinst: $numinst, panel: $panel) {\n res\n msg\n referenceId\n }\n}\n'})
('6: Unauthorized request for current capabilities.', {'errors': [{'message': '6: Unauthorized request for current capabilities.', 'name': 'ApiError', 'time_thrown': '2024-09-01T16:05:25.723Z', 'data': {'res': 'ERROR', 'err': '6', 'status': 401}, 'path': ['xSCheckAlarmStatus']}], 'data': {'xSCheckAlarmStatus': None}}, {'app': '{"appVersion": "10.102.0", "origin": "native"}', 'User-Agent': 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.124 Safari/537.36 Edg/102.0.1245.41', 'X-APOLLO-OPERATION-ID': '64c0ffaed5f21fd45b2c67b113a8a1e86e33e94adc119e92a2018ede10913fd676302541ee1f2493fc6dfdda507e177b0008f957252e0a4b3be708ab41220fa9', 'X-APOLLO-OPERATION-NAME': 'CheckAlarmStatus', 'extension': '{"mode":"full"}', 'numinst': '2330997', 'panel': 'SDVFAST', 'X-Capabilities': 'eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJlMTBiNGJkNy1jNGJjLTQ1YTctYmZmNy02NDVjMTMzYjE3MDUiLCJpYXQiOjE3MjUyMDU5OTYsImV4cCI6MTcyNTIwNjc4Miwicm9sZSI6Ik9XTkVSIiwiaW5zIjoiMjMzMDk5NyIsImNhcCI6WyJFU1RJTlYiLCJBUk1EQVkiLCJBUk1OSUdIVCIsIkFSTSIsIkRJWSIsIkdDIiwiQVNJIiwiRVNUIiwiVU5QUk9URUNUIiwiREFSTSIsIklOUyIsIklNRyIsIk5PVCIsIkFDVCIsIkNPTkYiLCJSRUZFUlJBTFBST0dSQU0iLCJEWU5BTUlDSU5GTyIsIk9MUyIsIlNFQ09ORElOU1RBTExBRCIsIlNNQVJUTk9UIiwiS0VZIiwiQ0FNRVJBUyIsIlBMQU4iLCJNWVNEIiwiUEFORUxDT05GIiwiU0NIIiwiQklMTFMiLCJJTlNUV09SRFMiLCJDT05GU0VSViIsIlBBWU1FTlRHIiwiV0hBVE5FVyIsIkNPTlRNR1JGQVEiLCJDT05UTUdSRE9XTiIsIkNPTlRNR1JNWVNFUlYiLCJXSEFUU0FQUCIsIlVQRENVRU5FWFRJTUUiLCJUSU1FTElORSIsIk5PVENPTkYiLCJERVZJQ0VTQ09ORiIsIlJFTUlOREVSUyIsIklOQVBQQ0FNUEFJR04iLCJBUk1JTlRGUEFSVCIsIkFSTVBBUlRGSU5UIiwiREVBQ1RJVkFURVpPTkUiXX0.y305UOZ_KOee0mU4_k-zZYbCpu-Wy3QHHYjs1wjNTdg', 'auth': '{"loginTimestamp": 1725206723201, "user": "01381380565", "id": "OWA_______________01381380565_______________202491185210126", "country": "IT", "lang": "it", "callby": "OWA_10", "hash": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMTM4MTM4MDU2NSIsImNudCI6IklUIiwiY2J5IjoiT1dBXzEwIiwidmVyIjoiMTAuMTAyLjAiLCJ1c3JpZCI6IjM0MzI2MjIiLCJqdGkiOiIwY2Y0MWE2Ni0xMmEzLTQxOTQtYjI2Ny1kZTIyZjBmNWIzZDMiLCJpYXQiOjE3MjUyMDY3MjIsImV4cCI6MTcyNTIwNzYyMn0.dCYU8rsjT8FYSHBb-ApiIAbXWhyZsBgOJ7XSdx8pDFI"}'}, {'operationName': 'CheckAlarmStatus', 'variables': {'numinst': '2330997', 'panel': 'SDVFAST', 'referenceId': 'cae7f784-5750-441b-bae8-dfcc7de22363', 'idService': '11', 'counter': 3}, 'query': 'query CheckAlarmStatus($numinst: String!, $idService: String!, $panel: String!, $referenceId: String!) {\n xSCheckAlarmStatus(numinst: $numinst, idService: $idService, panel: $panel, referenceId: $referenceId) {\n res\n msg\n status\n numinst\n protomResponse\n protomResponseDate\n }\n}\n'})
('alarm-manager.alarm_process_error', {'errors': [{'message': 'alarm-manager.alarm_process_error', 'name': 'ApiError', 'time_thrown': '2024-09-01T16:17:30.308Z', 'data': {'res': 'ERROR', 'err': '10', 'status': 500}, 'path': ['xSCheckAlarm']}], 'data': {'xSCheckAlarm': None}}, {'app': '{"appVersion": "10.102.0", "origin": "native"}', 'User-Agent': 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.124 Safari/537.36 Edg/102.0.1245.41', 'X-APOLLO-OPERATION-ID': '64c0ffaed5f21fd45b2c67b113a8a1e86e33e94adc119e92a2018ede10913fd676302541ee1f2493fc6dfdda507e177b0008f957252e0a4b3be708ab41220fa9', 'X-APOLLO-OPERATION-NAME': 'CheckAlarm', 'extension': '{"mode":"full"}', 'numinst': '2331058', 'panel': 'SDVFAST', 'X-Capabilities': 'eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJiMGUzYTkyOS02YzRlLTQ3MDEtOGYzYS1hMjNiMjYwYWEzMDgiLCJpYXQiOjE3MjUyMDY3MjMsImV4cCI6MTcyNTIwNzYyMiwicm9sZSI6Ik9XTkVSIiwiaW5zIjoiMjMzMTA1OCIsImNhcCI6WyJFU1RJTlYiLCJBUk1EQVkiLCJBUk1OSUdIVCIsIlBFUkkiLCJBUk0iLCJESVkiLCJHQyIsIkFTSSIsIkVTVCIsIlVOUFJPVEVDVCIsIkRBUk0iLCJJTlMiLCJJTUciLCJOT1QiLCJBQ1QiLCJDT05GIiwiUkVGRVJSQUxQUk9HUkFNIiwiRFlOQU1JQ0lORk8iLCJPTFMiLCJTRUNPTkRJTlNUQUxMQUQiLCJTTUFSVE5PVCIsIktFWSIsIkNBTUVSQVMiLCJQTEFOIiwiTVlTRCIsIlBBTkVMQ09ORiIsIlNDSCIsIkJJTExTIiwiSU5TVFdPUkRTIiwiQ09ORlNFUlYiLCJQQVlNRU5URyIsIldIQVRORVciLCJDT05UTUdSRkFRIiwiQ09OVE1HUkRPV04iLCJDT05UTUdSTVlTRVJWIiwiV0hBVFNBUFAiLCJVUERDVUVORVhUSU1FIiwiVElNRUxJTkUiLCJOT1RDT05GIiwiREVWSUNFU0NPTkYiLCJSRU1JTkRFUlMiLCJJTkFQUENBTVBBSUdOIiwiQVJNSU5URlBBUlQiLCJBUk1QQVJURklOVCIsIkRFQUNUSVZBVEVaT05FIl19.4X9A6AjuB5McgKgKAdWTjtem7Z1mrWvVjLwPfB8R9rU', 'auth': '{"loginTimestamp": 1725206723201, "user": "01381380565", "id": "OWA_______________01381380565_______________2024911817795755", "country": "IT", "lang": "it", "callby": "OWA_10", "hash": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMTM4MTM4MDU2NSIsImNudCI6IklUIiwiY2J5IjoiT1dBXzEwIiwidmVyIjoiMTAuMTAyLjAiLCJ1c3JpZCI6IjM0MzI2MjIiLCJqdGkiOiIwY2Y0MWE2Ni0xMmEzLTQxOTQtYjI2Ny1kZTIyZjBmNWIzZDMiLCJpYXQiOjE3MjUyMDY3MjIsImV4cCI6MTcyNTIwNzYyMn0.dCYU8rsjT8FYSHBb-ApiIAbXWhyZsBgOJ7XSdx8pDFI"}'}, {'operationName': 'CheckAlarm', 'variables': {'numinst': '2331058', 'panel': 'SDVFAST'}, 'query': 'query CheckAlarm($numinst: String!, $panel: String!) {\n xSCheckAlarm(numinst: $numinst, panel: $panel) {\n res\n msg\n referenceId\n }\n}\n'})
('6: Unauthorized request for current capabilities.', {'errors': [{'message': '6: Unauthorized request for current capabilities.', 'name': 'ApiError', 'time_thrown': '2024-09-01T16:19:25.007Z', 'data': {'res': 'ERROR', 'err': '6', 'status': 401}, 'path': ['xSCheckAlarmStatus']}], 'data': {'xSCheckAlarmStatus': None}}, {'app': '{"appVersion": "10.102.0", "origin": "native"}', 'User-Agent': 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.124 Safari/537.36 Edg/102.0.1245.41', 'X-APOLLO-OPERATION-ID': '64c0ffaed5f21fd45b2c67b113a8a1e86e33e94adc119e92a2018ede10913fd676302541ee1f2493fc6dfdda507e177b0008f957252e0a4b3be708ab41220fa9', 'X-APOLLO-OPERATION-NAME': 'CheckAlarmStatus', 'extension': '{"mode":"full"}', 'numinst': '2330997', 'panel': 'SDVFAST', 'X-Capabilities': 'eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI2ZGNhODEwMi01M2MzLTQzZGMtODY4Yi01NjZjOTliMDU1YWEiLCJpYXQiOjE3MjUyMDY4MzYsImV4cCI6MTcyNTIwNzYyMiwicm9sZSI6Ik9XTkVSIiwiaW5zIjoiMjMzMDk5NyIsImNhcCI6WyJFU1RJTlYiLCJBUk1EQVkiLCJBUk1OSUdIVCIsIkFSTSIsIkRJWSIsIkdDIiwiQVNJIiwiRVNUIiwiVU5QUk9URUNUIiwiREFSTSIsIklOUyIsIklNRyIsIk5PVCIsIkFDVCIsIkNPTkYiLCJSRUZFUlJBTFBST0dSQU0iLCJEWU5BTUlDSU5GTyIsIk9MUyIsIlNFQ09ORElOU1RBTExBRCIsIlNNQVJUTk9UIiwiS0VZIiwiQ0FNRVJBUyIsIlBMQU4iLCJNWVNEIiwiUEFORUxDT05GIiwiU0NIIiwiQklMTFMiLCJJTlNUV09SRFMiLCJDT05GU0VSViIsIlBBWU1FTlRHIiwiV0hBVE5FVyIsIkNPTlRNR1JGQVEiLCJDT05UTUdSRE9XTiIsIkNPTlRNR1JNWVNFUlYiLCJXSEFUU0FQUCIsIlVQRENVRU5FWFRJTUUiLCJUSU1FTElORSIsIk5PVENPTkYiLCJERVZJQ0VTQ09ORiIsIlJFTUlOREVSUyIsIklOQVBQQ0FNUEFJR04iLCJBUk1JTlRGUEFSVCIsIkFSTVBBUlRGSU5UIiwiREVBQ1RJVkFURVpPTkUiXX0.xzHJlRGqigiDQ5ZUWgY8zP-YGJq0rpp6UPsHm7Zy6Ic', 'auth': '{"loginTimestamp": 1725207562938, "user": "01381380565", "id": "OWA_______________01381380565_______________2024911819663972", "country": "IT", "lang": "it", "callby": "OWA_10", "hash": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMTM4MTM4MDU2NSIsImNudCI6IklUIiwiY2J5IjoiT1dBXzEwIiwidmVyIjoiMTAuMTAyLjAiLCJ1c3JpZCI6IjM0MzI2MjIiLCJqdGkiOiJhMjNjYjI3Yi0wMjc1LTRiZTctOGEyMi0zZmMzZGQ5ZmVjODciLCJpYXQiOjE3MjUyMDc1NjIsImV4cCI6MTcyNTIwODQ2Mn0.TJldecg9Cs0R59NY3bjeLRfWD5_nPux0ZDXdy3nMCXc"}'}, {'operationName': 'CheckAlarmStatus', 'variables': {'numinst': '2330997', 'panel': 'SDVFAST', 'referenceId': 'db00b1a8-f300-4613-b3dc-4ea44458ed29', 'idService': '11', 'counter': 3}, 'query': 'query CheckAlarmStatus($numinst: String!, $idService: String!, $panel: String!, $referenceId: String!) {\n xSCheckAlarmStatus(numinst: $numinst, idService: $idService, panel: $panel, referenceId: $referenceId) {\n res\n msg\n status\n numinst\n protomResponse\n protomResponseDate\n }\n}\n'})
('6: Unauthorized request for current capabilities.', {'errors': [{'message': '6: Unauthorized request for current capabilities.', 'name': 'ApiError', 'time_thrown': '2024-09-01T16:33:24.368Z', 'data': {'res': 'ERROR', 'err': '6', 'status': 401}, 'path': ['xSCheckAlarmStatus']}], 'data': {'xSCheckAlarmStatus': None}}, {'app': '{"appVersion": "10.102.0", "origin": "native"}', 'User-Agent': 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.124 Safari/537.36 Edg/102.0.1245.41', 'X-APOLLO-OPERATION-ID': '64c0ffaed5f21fd45b2c67b113a8a1e86e33e94adc119e92a2018ede10913fd676302541ee1f2493fc6dfdda507e177b0008f957252e0a4b3be708ab41220fa9', 'X-APOLLO-OPERATION-NAME': 'CheckAlarmStatus', 'extension': '{"mode":"full"}', 'numinst': '2330997', 'panel': 'SDVFAST', 'X-Capabilities': 'eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIyODY0MGRiMi0xNGRlLTQ0ZmEtOTlhMi02OTk3YWY2Zjg1MmIiLCJpYXQiOjE3MjUyMDc2NzcsImV4cCI6MTcyNTIwODQ2Miwicm9sZSI6Ik9XTkVSIiwiaW5zIjoiMjMzMDk5NyIsImNhcCI6WyJFU1RJTlYiLCJBUk1EQVkiLCJBUk1OSUdIVCIsIkFSTSIsIkRJWSIsIkdDIiwiQVNJIiwiRVNUIiwiVU5QUk9URUNUIiwiREFSTSIsIklOUyIsIklNRyIsIk5PVCIsIkFDVCIsIkNPTkYiLCJSRUZFUlJBTFBST0dSQU0iLCJEWU5BTUlDSU5GTyIsIk9MUyIsIlNFQ09ORElOU1RBTExBRCIsIlNNQVJUTk9UIiwiS0VZIiwiQ0FNRVJBUyIsIlBMQU4iLCJNWVNEIiwiUEFORUxDT05GIiwiU0NIIiwiQklMTFMiLCJJTlNUV09SRFMiLCJDT05GU0VSViIsIlBBWU1FTlRHIiwiV0hBVE5FVyIsIkNPTlRNR1JGQVEiLCJDT05UTUdSRE9XTiIsIkNPTlRNR1JNWVNFUlYiLCJXSEFUU0FQUCIsIlVQRENVRU5FWFRJTUUiLCJUSU1FTElORSIsIk5PVENPTkYiLCJERVZJQ0VTQ09ORiIsIlJFTUlOREVSUyIsIklOQVBQQ0FNUEFJR04iLCJBUk1JTlRGUEFSVCIsIkFSTVBBUlRGSU5UIiwiREVBQ1RJVkFURVpPTkUiXX0.HiJbA4XCoDxanauuJII2k-lVhdIdp1vFtt8SHlchB2o', 'auth': '{"loginTimestamp": 1725208402739, "user": "01381380565", "id": "OWA_______________01381380565_______________2024911833236580", "country": "IT", "lang": "it", "callby": "OWA_10", "hash": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMTM4MTM4MDU2NSIsImNudCI6IklUIiwiY2J5IjoiT1dBXzEwIiwidmVyIjoiMTAuMTAyLjAiLCJ1c3JpZCI6IjM0MzI2MjIiLCJqdGkiOiIyZWY2YzNlZi1jYjQ5LTQyNjEtYTdjMC1mYTIwZTYxNWVjOTYiLCJpYXQiOjE3MjUyMDg0MDIsImV4cCI6MTcyNTIwOTMwMn0.c4EWV-VfPZR-GBqZg0CW4LE5RTSPIppWndJqQL9hUXQ"}'}, {'operationName': 'CheckAlarmStatus', 'variables': {'numinst': '2330997', 'panel': 'SDVFAST', 'referenceId': '6c6859f5-2140-4602-a35f-b3c280bf2061', 'idService': '11', 'counter': 3}, 'query': 'query CheckAlarmStatus($numinst: String!, $idService: String!, $panel: String!, $referenceId: String!) {\n xSCheckAlarmStatus(numinst: $numinst, idService: $idService, panel: $panel, referenceId: $referenceId) {\n res\n msg\n status\n numinst\n protomResponse\n protomResponseDate\n }\n}\n'})

**Comment by guerrerotook** [comment]
As you can see on the logs, you are using a user in your integration that doesn't support those capabilities. 

**Unauthorized request for current capabilities**

**Comment by guerrerotook** [comment]
As you can see on the logs, you are using a user in your integration that doesn't support those capabilitites. 

**Unauthorized request for current capabilities**
