### ISSUE TITLE
doesn't  work inUK 

### ISSUE THREAD

**Issue by kiranbhakre** [guerrerotook/securitas-direct-new-api#25]
i tried to add the URL and check but it is not working. just we can arm the system but not disarm it.

**Comment by guerrerotook** [comment]
Do you have any kind of log, error or something that can help me identify why is not working?

**Comment by kiranbhakre** [comment]
i have created the pull request for the domain addition to UK. "UK Domain addition #37"

**Comment by guerrerotook** [comment]
Nice, thanks very much for the PR. I just create the new release. Closing the issue.
