### ISSUE TITLE
Deprectaed in  2025.11

### ISSUE THREAD

**Issue by cdnarbona** [guerrerotook/securitas-direct-new-api#255]
Logger: homeassistant.const
Source: helpers/deprecation.py:222
First occurred: 10:43:40 (7 occurrences)
Last logged: 10:43:40

    STATE_ALARM_ARMED_HOME was used from securitas, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.ARMED_HOME instead, please report it to the author of the 'securitas' custom integration
    STATE_ALARM_ARMED_NIGHT was used from securitas, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.ARMED_NIGHT instead, please report it to the author of the 'securitas' custom integration
    STATE_ALARM_ARMING was used from securitas, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.ARMING instead, please report it to the author of the 'securitas' custom integration
    STATE_ALARM_DISARMED was used from securitas, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.DISARMED instead, please report it to the author of the 'securitas' custom integration
    STATE_ALARM_DISARMING was used from securitas, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.DISARMING instead, please report it to the author of the 'securitas' custom integration

**Comment by guerrerotook** [comment]
Thanks very much for raising this. Let me take care of this and I will update the ingration!
