### ISSUE TITLE
Los cambios no se actualizan en Home Assistant

### ISSUE THREAD

**Issue by alessbarb** [guerrerotook/securitas-direct-new-api#26]
Buenas, los cambios que haces al componente no se me actualizan en Home Assistant. Creo que debes cambiar la versión en algún fichero para que automáticamente salte la actualización.

**Comment by alessbarb** [comment]
Pues ahora estoy forzando la descarga:

![image](https://user-images.githubusercontent.com/26366705/151418794-57ea6ace-fb36-45f6-b2de-1f6e5c93ee06.png)

Pero otros componentes me avisan de las actualizaciones y el detalle de los cambios realizados, por ejemplo:

![image](https://user-images.githubusercontent.com/26366705/151418586-c7c926c7-1b67-4967-a44e-d55265b068cc.png)

![image](https://user-images.githubusercontent.com/26366705/151418657-260c3583-bb53-4c43-aec9-e4234554faee.png)

![image](https://user-images.githubusercontent.com/26366705/151418724-b6b3fbf0-a25a-4bc9-be9f-9d0ce44a001a.png)

**Comment by guerrerotook** [comment]
Acabo de lanzar una nueva versión #33 dime si aparece en el HACS

**Comment by alessbarb** [comment]
Perfecto:

![image](https://user-images.githubusercontent.com/26366705/153775462-c8a522dc-20d4-4cbb-8ade-9ddea45b916c.png)
