### ISSUE TITLE
Alarm panel not updating status.

### ISSUE THREAD

**Issue by agaleraib** [guerrerotook/securitas-direct-new-api#36]
I've noticed that the HA alarm panel does not update the status after the first attempt of arming/disarming the alarm.

For instance, when calling the call service "alarm_control_panel.alarm_arm_night", the alarm will indeed be armed (I can see the ARMED NIGHT status in the Verisure app) but the HA alarm panel will continue showing "Disarmed". If I send a second time the he call service "alarm_control_panel.alarm_arm_night" then the HA panel will show the correct status.

The same behaviour when attempting to disarm the alarm with a call service "alarm_control_panel.alarm_disarm", the first time the  HA panel will keep on showing "ARMED NIHGT" (or whatever other status) until I send a second call service "alarm_control_panel.alarm_disarm", then the status will refresh to "Disarmed"

I have tried with both configurations:

alarm_control_panel.alarm_disarm: true
alarm_control_panel.alarm_disarm: false 

Let me know if you need further details.

Thank you,

**Comment by guerrerotook** [comment]
Yes, I realized this. Happen to me as well and working on it. Thanks!

**Comment by guerrerotook** [comment]
Solved in this latest release, #40
