### ISSUE TITLE
Multiple request

### ISSUE THREAD

**Issue by iuhorts** [guerrerotook/securitas-direct-new-api#46]
When i active the alarm via home assistant most of the times Securitas direct calls me due to multiple requests launched at same time.
This told me securitas is done due to do a request without whait the previous one is resolved.
Could it be controllated.
I recieve at least 2 daily calls from securitas.🤣

**Comment by guerrerotook** [comment]
You can add to your configuration to avoid this.

```yaml
securitas:
  check_alarm_panel: false
```

As described in the [readme.md ](https://github.com/guerrerotook/securitas-direct-new-api#readme)file.
