### ISSUE TITLE
Three Securitas sensors (temp. humidity & air Quality) unavailable after last update! 

### ISSUE THREAD

**Issue by tutmosisiii** [guerrerotook/securitas-direct-new-api#47]
![Screenshot_20220406_230612](https://user-images.githubusercontent.com/99619179/162070955-ae10416d-49f7-4a5c-95fc-8f9c193e5153.jpg)

**Comment by tutmosisiii** [comment]
The securitas sensors are now recognized as devices, without an asociated entity, abosutely disfunctional

**Comment by guerrerotook** [comment]
Yes, there was a change in the API. I just fixed in the release #49
