### ISSUE TITLE
problemas para iniciar la sesión

### ISSUE THREAD

**Issue by JMolina64** [guerrerotook/securitas-direct-new-api#5]
Hola Luis,
He instalado tu modulo y cuando arranco el HA me devuelve estos errores....  

1.-

This error originated from a custom integration.

Logger: custom_components.securitas_direct.securitas_direct_new_api.apimanager
Source: custom_components/securitas_direct/securitas_direct_new_api/apimanager.py:89
Integration: Securitas Direct (documentation, issues)
First occurred: 8:02:12 PM (1 occurrences)
Last logged: 8:02:12 PM

Hemos tenido problemas para identificarle, por favor, cierre la sesión y vuelva a iniciarla.

2.-

Logger: homeassistant.components.alarm_control_panel
Source: custom_components/securitas_direct/securitas_direct_new_api/apimanager.py:173
Integration: Alarm control panel (documentation, issues)
First occurred: 8:02:13 PM (1 occurrences)
Last logged: 8:02:13 PM

Error while setting up securitas_direct platform for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/securitas_direct/alarm_control_panel.py", line 55, in setup_platform
    current_state: CheckAlarmStatus = hub.update_overview(
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 195, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/securitas_direct/__init__.py", line 114, in update_overview
    referenceId: str = self.session.checkAlarm(Installation)
  File "/config/custom_components/securitas_direct/securitas_direct_new_api/apimanager.py", line 173, in checkAlarm
    return result_json["data"]["xSCheckAlarm"]["referenceId"]
TypeError: 'NoneType' object is not subscriptable

Me puedes echar una mano...?
Gracias

**Comment by guerrerotook** [comment]
Intenta iniciar sesión [aquí ](https://customers.securitasdirect.es/owa-static/login) y dime que te dice la página web. Es la misma API.

**Comment by jjmateof** [comment]
Buenas, tengo un problema similar. Me dice esto:

 Logger: custom_components.securitas_direct.securitas_direct_new_api.apimanager
Source: custom_components/securitas_direct/securitas_direct_new_api/apimanager.py:89
Integration: securitas_direct (documentation, issues)
First occurred: 00:23:10 (1 occurrences)
Last logged: 00:23:10
El usuario introducido no existe

Si pincho en el enlace que pones, puedo acceder perfectamente con mi usuario y contraseña.

Gracias por tu ayuda.

Saludos.

**Comment by guerrerotook** [comment]
@jjmateof y estas usando el mismo usuario y contraseña en la integración de HA? Asegúrate de que tienes la propiedad de lenguaje a ES a ver si eso afecta en algo. Tienes que poner exactamente la misma información de inicio de sesion que utilizas en la web en la configuración del Home Assitant.

**Comment by jjmateof** [comment]
Buenas,

Sí, uso el mismo usuario y contraseña que para acceder vía web (o a través de la app) a Securitas Direct. El idioma que tengo puesto es ES.

securitas_direct:
  username: !secret securitas_direct_username
  password: !secret securitas_direct_password
  code: !secret securitas_direct_code
  country: ES

A parte del error de ayer, tengo otro en el log cuando inicio HA.

Este es el primero que da

_Logger: homeassistant.setup
Source: custom_components/securitas_direct/securitas_direct_new_api/apimanager.py:121
Integration: securitas_direct (documentation, issues)
First occurred: 11:07:22 (1 occurrences)
Last logged: 11:07:22
Error during setup of component securitas_direct

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/securitas_direct/__init__.py", line 64, in setup
    if not HUB.login():
  File "/config/custom_components/securitas_direct/__init__.py", line 94, in login
    succeed: Tuple[bool, str] = self.session.login()
  File "/config/custom_components/securitas_direct/securitas_direct_new_api/apimanager.py", line 121, in login
    self.authentication_token = result_json["data"]["xSLoginToken"]["hash"]
TypeError: 'NoneType' object is not subscriptable_

Y este es el segundo.

_Este error se originó a partir de una integración personalizada.

Logger: custom_components.securitas_direct.securitas_direct_new_api.apimanager
Source: custom_components/securitas_direct/securitas_direct_new_api/apimanager.py:89
Integration: securitas_direct (documentation, issues)
First occurred: 11:07:19 (1 occurrences)
Last logged: 11:07:19

El usuario introducido no existe_

Gracias de nuevo.

Un saludo.

**Comment by JMolina64** [comment]
> Intenta iniciar sesión [aquí ](https://customers.securitasdirect.es/owa-static/login) y dime que te dice la página web. Es la misma API.

Hola Luis,

Gracias por contestar... He entrado al link sin problemas... he re-ininializado HA y siguen los dos errores..

1.- 

This error originated from a custom integration.

Logger: custom_components.securitas_direct.securitas_direct_new_api.apimanager
Source: custom_components/securitas_direct/securitas_direct_new_api/apimanager.py:89
Integration: Securitas Direct (documentation, issues)
First occurred: 11:18:41 AM (1 occurrences)
Last logged: 11:18:41 AM

Hemos tenido problemas para identificarle, por favor, cierre la sesión y vuelva a iniciarla.

2.-

Logger: homeassistant.components.alarm_control_panel
Source: custom_components/securitas_direct/securitas_direct_new_api/apimanager.py:173
Integration: Alarm control panel (documentation, issues)
First occurred: 11:18:43 AM (1 occurrences)
Last logged: 11:18:43 AM

Error while setting up securitas_direct platform for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/securitas_direct/alarm_control_panel.py", line 55, in setup_platform
    current_state: CheckAlarmStatus = hub.update_overview(
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 195, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/securitas_direct/__init__.py", line 114, in update_overview
    referenceId: str = self.session.checkAlarm(Installation)
  File "/config/custom_components/securitas_direct/securitas_direct_new_api/apimanager.py", line 173, in checkAlarm
    return result_json["data"]["xSCheckAlarm"]["referenceId"]
TypeError: 'NoneType' object is not subscriptable

**Comment by jjmateof** [comment]
Buenas,

Sí, en ese link con mi usuario y contraseña (los mismos datos que pongo en HA) accedo correctamente.

Gracias y un saludo.
Julio.

**Comment by guerrerotook** [comment]
> > Intenta iniciar sesión [aquí ](https://customers.securitasdirect.es/owa-static/login) y dime que te dice la página web. Es la misma API.
> 
> Hola Luis,
> 
> Gracias por contestar... He entrado al link sin problemas... he re-ininializado HA y siguen los dos errores..
> 
> 1.-
> 
> This error originated from a custom integration.
> 
> Logger: custom_components.securitas_direct.securitas_direct_new_api.apimanager Source: custom_components/securitas_direct/securitas_direct_new_api/apimanager.py:89 Integration: Securitas Direct (documentation, issues) First occurred: 11:18:41 AM (1 occurrences) Last logged: 11:18:41 AM
> 
> Hemos tenido problemas para identificarle, por favor, cierre la sesión y vuelva a iniciarla.
> 
> 2.-
> 
> Logger: homeassistant.components.alarm_control_panel Source: custom_components/securitas_direct/securitas_direct_new_api/apimanager.py:173 Integration: Alarm control panel (documentation, issues) First occurred: 11:18:43 AM (1 occurrences) Last logged: 11:18:43 AM
> 
> Error while setting up securitas_direct platform for alarm_control_panel Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform await asyncio.shield(task) File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/securitas_direct/alarm_control_panel.py", line 55, in setup_platform current_state: CheckAlarmStatus = hub.update_overview( File "/usr/src/homeassistant/homeassistant/util/**init**.py", line 195, in wrapper result = method(*args, **kwargs) File "/config/custom_components/securitas_direct/**init**.py", line 114, in update_overview referenceId: str = self.session.checkAlarm(Installation) File "/config/custom_components/securitas_direct/securitas_direct_new_api/apimanager.py", line 173, in checkAlarm return result_json["data"]["xSCheckAlarm"]["referenceId"] TypeError: 'NoneType' object is not subscriptable

¿Puedes activar los logs de DEBUG para ver las respuestas completas de JSON?

@JMolina64 cuidado con compartir esos logs que contiene información personal.

**Comment by JMolina64** [comment]
> 

Activado......

logger:
  logs:
    custom_components.securitas_direct: debug

pero no se ve nada que de ninguna información, ni con tail ni con grep, simplemente aparece la palabra "securitas".....

**Comment by JMolina64** [comment]
Arreglado. he cambiado el tipo de numinst de esto int(item["numinst"]). a esto item["numinst"] y desaparece el error.....

**Comment by guerrerotook** [comment]
Se ha actualizado el codigo varias veces desde que abriste la issue. Vuelve a copiar porque he añadido soporte para los Sentinels.

**Comment by JMolina64** [comment]
Disculpa Luis,

Pero sigue definido como integer. linea 154

 int(item["numinst"]),

**Comment by jjmateof** [comment]
Buenas,

A mí me sigue dando el mismo error de autenticación. No se vuestros username, pero el mío es parte de mi DNI y es numérico, por si sirve de algo. No se si los usersname de todos son parte de los DNIs, pero a mí no me han dado opción. Ese es el usuario que me dieron cuando me lo instalaron.

Gracias y un saludo.
