### ISSUE TITLE
Two Step authentication and authorized devices

### ISSUE THREAD

**Issue by manuelbarbosa** [guerrerotook/securitas-direct-new-api#52]
Portugal just enabled two factor authentication by SMS and authorized devices. I get Unauthorized error message when trying to login through the API

**Comment by sh4rks** [comment]
+1. Same in France, the integration don’t setup because it takes more than 60s

**Comment by guerrerotook** [comment]
The home assistant integration identify as a web app and not as a mobile app. I do have the second factor of authentication on my phone but not on the HA. What happen during the login process?

**Comment by manuelbarbosa** [comment]
I will check the error log message and post it here

**Comment by guerrerotook** [comment]
Thanks for the report, unfortunately until this happens to me, it's very difficult to debug remotely. Sorry for the inconvenience.

**Comment by siom7** [comment]
@guerrerotook If needed to debug remotely you can ask to me to do some tests :)

**Comment by guerrerotook** [comment]
> @guerrerotook Luis Guerrero Guirado FTE If needed to debug remotely you can ask to me to do some tests :)

That would be awesome @siom7, I have these two documents that explain how to capture requests from the web application. 

https://github.com/guerrerotook/securitas-direct-new-api/blob/main/docs/how_to_capture.md

https://github.com/guerrerotook/securitas-direct-new-api/blob/main/docs/new_operations.md

So, I would like you to fully login onto the website and export the request and the responses from the web app. **My only request is to be extremely careful because that may contain your login and password and I don't want that information to be leaked** . But you have the full end to end flow of the login with the SMS I can try to implement this.

**Comment by siom7** [comment]
@guerrerotook 

{
    "data":
    {
        "xSLoginToken":
        {
            "res":"OK",
            "msg":"Utilisateur correctement validé",
 "hash":"eyJhbGciOiJIUzI1NiJ9.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "lang":"FR",
            "legals":true,
            "mainUser":false,
            "changePassword":false,
            "needDeviceAuthorization":null
        }
    }
}

**Comment by siom7** [comment]
@guerrerotook And this when I check alarm status

`{
    "data":
    {
        "xSCheckAlarmStatus":
        {
            "res":"WAIT",
            "msg":"Demande en cours de traitement",
            "status":null,
            "numinst":null,
            "protomResponse":null,
            "protomResponseDate":null
        }
    }
}


{
    "data":
    {
        "xSCheckAlarmStatus":
        {
            "res":"OK",
            "msg":"Votre alarme est désactivée",
            "status":"0","numinst":"XXXXXXXX",
            "protomResponse":"D",
            "protomResponseDate":"2022-06-23 12:44:29.783"
        }
    }
}`

**Comment by guerrerotook** [comment]
Thanks very much. It happens to me as well, so now I can easily debug the two steps authentication.

**Comment by siom7** [comment]
Ok, let me know if you need me for testing :)

**Comment by TheGui01** [comment]
Hello,

Just made some adjustments on something else and rebooted My HA and it
works again !!

**Comment by guerrerotook** [comment]
> o refresh every 5m

Can you share what you did so I can modify the component and everyone can benefit?

**Comment by sh4rks** [comment]
I modify the line 45 in alarm_control_panel.py with SCAN_INTERVAL = timedelta(seconds=300)

**Comment by manuelbarbosa** [comment]
> I modify the line 45 in alarm_control_panel.py with SCAN_INTERVAL = timedelta(seconds=300)

How does changing the refresh interval fix a 2FA auth on this service!? I am confused...

**Comment by oborqueg** [comment]
Hi @sh4rks 
How did you modifyed the alarm_control_panel.py file? I can edit directli on Hassio? O i need to uninstall the integration, modify the lane 45 and then install the modifyed component?

Thank you in advance.

**Comment by siom7** [comment]
@oborqueg Please see this issue -> https://github.com/guerrerotook/securitas-direct-new-api/issues/57

You just have to wait…

**Comment by oborqueg** [comment]
@siom7 to wait for what? updated version?
I have the v3.1.0.0 and have the unathorized error :(

**Comment by siom7** [comment]
@oborqueg There is 2FA now to authenticate on Verisure API @guerrerotook is currently working on it.

**Comment by otistarda** [comment]
Still not working?

**Comment by BertMart71** [comment]
I just installed the integration, and same error.

[custom_components.securitas.securitas_direct_new_api.apimanager] **Unauthorized**

Not working for me: line 45 in alarm_control_panel.py with SCAN_INTERVAL = timedelta(seconds=300)

Any update?

**Comment by siom7** [comment]
@BertMart71 https://github.com/guerrerotook/securitas-direct-new-api/issues/52
