### ISSUE TITLE
No puedo armar total

### ISSUE THREAD

**Issue by pmcastro10** [guerrerotook/securitas-direct-new-api#55]
Buenos días,

En estos momentos tengo dos problemas. El primero lo he tenido siempre y es que ninguna de las opciones de armado me arma en modo total, tanto interior cómo exterior. Y el segundo, que me ha empezado hace poco, es que no me desarma. En ninguno de los dos casos da mensaje de error.
Se agradece cualquier sugerencia.
Gracias.

**Comment by guerrerotook** [comment]
Sigues teniendo estos problemas?

**Comment by pmcastro10** [comment]
Buenas,

Lo del armado total sigue siendo imposible. Pero ahora puedo desarmar, no sé si es debido a la actualización o a algo que tenía mal antes.

Saludos.
