### ISSUE TITLE
Compatible with homebridge

### ISSUE THREAD

**Issue by lenny005** [guerrerotook/securitas-direct-new-api#59]
Hello could you please make your addon compatible with homebridge ?

there is an equivalent but it was not updated since 2 years ans it is making the verisure system unresponsive.
https://github.com/ptz0n/homebridge-securitas-direct#readme

**Comment by guerrerotook** [comment]
What is homebridge?

**Comment by lenny005** [comment]
Basically it is a mini HA only for homekit.

« Homebridge is a lightweight NodeJS server you can run on your home network that emulates the iOS HomeKit API. It supports Plugins, which are community-contributed modules that provide a basic bridge from HomeKit to various 3rd-party APIs provided by manufacturers of "smart home" devices. »

If you could transfer your work in a plugin, or work from the one i pin above, it would be awesome.

i asked for the main dev to update his 2 years old code, here is his answer : 

https://github.com/ptz0n/homebridge-securitas-direct/issues/11#issuecomment-1160402550

i can support you as needed !

**Comment by guerrerotook** [comment]
I have enabled HomeKit integration in my Home Assistant and it works perfectly, even the Alarm. That is why I was confused.

**Comment by andr1u** [comment]
> Hello could you please make your addon compatible with homebridge ?
> 
> there is an equivalent but it was not updated since 2 years ans it is making the verisure system unresponsive. https://github.com/ptz0n/homebridge-securitas-direct#readme

Works well with HomeKit. I've configured in YAML.

# Example configuration.yaml entry configuring HomeKit
homekit:
  - filter:
    entity_config:
      alarm_control_panel.home:
        code: 1234

> I have enabled HomeKit integration in my Home Assistant and it works perfectly, even the Alarm. That is why I was confused.

I can confirm, it works well in HomeKit. When integration worked some time ago... 😉

Nice work @guerrerotook. Keep pushing for the 2FA!

**Comment by andr1u** [comment]
> > Hello could you please make your addon compatible with homebridge ?
> 
> > 
> 
> > there is an equivalent but it was not updated since 2 years ans it is making the verisure system unresponsive. https://github.com/ptz0n/homebridge-securitas-direct#readme
> 
> 
> 
> Works well with HomeKit. I've configured in YAML.
> 
> 
> 
> ```
> 
> # Example configuration.yaml entry configuring HomeKit
> 
> homekit:
> 
>   - filter:
> 
>     entity_config:
> 
>       alarm_control_panel.home:
> 
>         code: 1234
> 
> ```
> 
> 
> 
> > I have enabled HomeKit integration in my Home Assistant and it works perfectly, even the Alarm. That is why I was confused.
> 
> 
> 
> I can confirm, it works well in HomeKit. When integration worked some time ago... 😉
> 
> 
> 
> Nice work @guerrerotook. Keep pushing for the 2FA!
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

I can confirm that still works perfect with the new 2FA release on HomeKit. 

Can close this issue @guerrerotook.
