### ISSUE TITLE
Issues in authentication (Portugal)

### ISSUE THREAD

**Issue by philder** [guerrerotook/securitas-direct-new-api#61]
Hi there! I'm trying to put it to work in Portugal but I'm getting this issues:

<img width="598" alt="Captura de ecrã 2022-06-23, às 08 00 06" src="https://user-images.githubusercontent.com/49433063/175236316-eee03836-b75b-4764-98b2-71576c285778.png">

<img width="406" alt="Captura de ecrã 2022-06-23, às 08 00 22" src="https://user-images.githubusercontent.com/49433063/175236355-35e4c964-4ace-48d7-9e80-9b98277eae07.png">

This is my configuration:

`securitas:
  username: !secret securitas_username
  password: !secret securitas_password
  code: !secret securitas_code
  country: PT`

Thank you!

**Comment by guerrerotook** [comment]
Thanks for the issue, but I'm going to close the issue because it's related to this one. #52 please follow updates in there.
