### ISSUE TITLE
Unable to find services.yaml for the securitas integration

### ISSUE THREAD

**Issue by meazzaflavio** [guerrerotook/securitas-direct-new-api#63]
Hello,

After configuring the configuration.yaml file and restarted home assistant I see the integration loaded but with no device or entities and in the registry I found this error:

Logger: homeassistant.helpers.service
Source: helpers/service.py:430 
First occurred: 16:06:13 (1 occurrences) 
Last logged: 16:06:13

Unable to find services.yaml for the securitas integration

**Comment by siom7** [comment]
https://github.com/guerrerotook/securitas-direct-new-api/issues/57#issuecomment-1179770156

**Comment by meazzaflavio** [comment]
Oh ok sorry, thanks for informing
