### ISSUE TITLE
Waiting on integrations to complete setup: securitas

### ISSUE THREAD

**Issue by lfnovo** [guerrerotook/securitas-direct-new-api#64]
Hello folks.. I installed the component according to the docs but, when I reload HA, it keeps getting this message and never finishes loading the component. Any idea on how to debug the issue?

**Comment by siom7** [comment]
@lfnovo https://github.com/guerrerotook/securitas-direct-new-api/issues/57

**Comment by lfnovo** [comment]
Duplicate #57
