### ISSUE TITLE
I can not disarm

### ISSUE THREAD

**Issue by aewnor** [guerrerotook/securitas-direct-new-api#68]
Hello, I updated to last release. All the arms working fine, but when i tried to disarm, it seems homeassistant do nothing.

Somebody know how can fixed it?

Thank you.

**Comment by oborqueg** [comment]
Same issue here

**Comment by DNKROZ** [comment]
I can confirm this, same problem here, I can arm but not disarm.

Have tried several config flows and also yaml configuration, no luck, with and without alarm code and also status checking.

But it's nice to have this working at least for arming :)

**Comment by guerrerotook** [comment]
Let me take a look !

**Comment by guerrerotook** [comment]
Solved on this commit, https://github.com/guerrerotook/securitas-direct-new-api/commit/9a8fd6c9ca0295136b31cc892e2bdf41ba2571cb please update the component.

**Comment by siom7** [comment]
Many thanks ! It's working perfectly now ! :)
