### ISSUE TITLE
Addition of Brazil domain

### ISSUE THREAD

**Issue by pedropaislopes** [guerrerotook/securitas-direct-new-api#69]
Hi!

I'm using Securitas Direct in my country (Brazil), but ApiDomain for my country is a special address (like others).

This is the address that should be added to `securitas_direct_new_api/domains.py`:

`"br": "https://customers.verisure.com.br/owa-api/graphql",`

On `self.domains` dict.

Thanks a lot for the good work!

Cheers!

**Comment by guerrerotook** [comment]
Thanks for the suggestion. Added the endpoint to the list of endpoints. 

https://github.com/guerrerotook/securitas-direct-new-api/commit/3d53f8476851027655aed5d0a93db6cf201e192a

**Comment by guerrerotook** [comment]
Here is the release. 
https://github.com/guerrerotook/securitas-direct-new-api/releases/tag/v2.0.0.2
