### ISSUE TITLE
Can't Disarm

### ISSUE THREAD

**Issue by bilbon0bud** [guerrerotook/securitas-direct-new-api#70]
Hello

I can have my alarm state and arm my alarm with home assistant, but i can't disarm it.
I in france, i try with the 2.0.0.2 release.

Best Regards

**Comment by siom7** [comment]
I’m in France too and I can do both actions with the lastest version.

**Comment by bilbon0bud** [comment]
I try this:
1/ delete integration
2/ uninstall plugin in HACS
3/ reboot
4/ install plugin in HACS
5/ reboot
6/ configure integration

i can select my phone but... when give the code backto the app i got an error.

try this with 2.0.0.0 and 2.0.0.2 

an idea of what i m missing ?

**Comment by bilbon0bud** [comment]
Hello

I delete the plugins, then withe  he last update of HA, 
i have auto detection of my alarm, i configure it and everything was Ok now.

SO there no more any problem for me :)

thanks for your help.
