### ISSUE TITLE
New securitas-direct-new-api intergration Version 2.0.0.2 is not able to disarm the perimetral zone 

### ISSUE THREAD

**Issue by Javvaz** [guerrerotook/securitas-direct-new-api#71]
Once the new version of securitas-direct-new-appi integration is installed, I am able to arm and disarm the alarm, such through out the control panel or scripts. However I am not able nevermore to disarm the perimetral zone. In other words, the integration is not able to diarm when the status is armed_custom_bypass.

You can find the corresponding debug logs in the attach file (those logs correpond to the arming and disarming the perimetral zone)

Thanks in advance and regards.

![HomeAssistant Logs](https://user-images.githubusercontent.com/98023153/188664766-fc7865bc-8ed3-4c54-9243-0764dfd4001d.png)

**Comment by Javvaz** [comment]
First of all thank you for your work.
I am not sure if you have had time to take a look this issue, but it is still there. Let me know if you need anything else.

Thanks in advance and regards.

**Comment by Xeovar** [comment]
I have the same issue, arming works ok, disarming doesnt.

**Comment by Javvaz** [comment]
Any progress on this, Luis.
Do you need anything from our side?
Can we help you on any way?

**Comment by Javvaz** [comment]
Thanks Luis for your work, it is great!!
Regarding this issue I tested it with the version 2.1 and it is still happening. It is possible to arm the Perimetral Zone, but there is not way to disarm it.

I would appreciate if you figure out how to solve this.

Thanks and regards.

**Comment by cantupaz** [comment]
Will fix as part of https://github.com/guerrerotook/securitas-direct-new-api/issues/193

**Comment by cantupaz** [comment]
The latest release (2.7.1) should have fixed this.
