### ISSUE TITLE
Not getting entities

### ISSUE THREAD

**Issue by philder** [guerrerotook/securitas-direct-new-api#81]
Hello.

I've installed the integration from HACS, then I added the configuration.yaml. Restarted the HA.
When HA started I configured the new integration. Everything went well unitl I restarted. HA have "discovered" again the "new" integration.
I tried a different method: Installed by HACS, left the configuration.yaml part and added Securitas Direct in the Integrations by clicking in the Plus button. Restarted. Everything went well but I didn't get any entities.

<img width="286" alt="Captura de ecrã 2022-09-16, às 17 51 43" src="https://user-images.githubusercontent.com/49433063/190689829-eac79d5d-cb8d-4cb6-90fa-5ec4abaa9346.png">

I'm in Portugal by the way.

Thank you!

**Comment by guerrerotook** [comment]
Thanks, do you have any other logs in the homeassistant.log in your installation. Something that I can work with?

**Comment by TheGui01** [comment]
Hello,

Same issue here : 
![image](https://user-images.githubusercontent.com/99127784/190846987-1b060ef8-f4ef-41ae-9e82-6fa492913358.png)

The only log found at the restart is :
 2022-09-17 09:57:26.952 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration securitas which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-09-17 09:58:03.840 WARNING (SyncWorker_9) [homeassistant.helpers.service] Unable to find services.yaml for the securitas integration

The integration with my user is the functional one. 
The one named Securitas direct keeps appearing as a new device that can't be ignored and it pops at every restart in HA notification.

**Comment by josecarre** [comment]
Hi,

This this you mention @TheGui01 :
`The one named Securitas direct keeps appearing as a new device that can't be ignored and it pops at every restart in HA notification.`

Is also happening to me. I have my alarm configured right, working fine... but it always detects a new/second installation in which sms code never work... so I just can ignore this new devices detected and live with the pain of the notification 😆

**Comment by alnavasa** [comment]
Had this issue, remove everything form the cofiguration yaml solved the issue

**Comment by TheGui01** [comment]
Hello,

Thanks for this tips, it works on my side as well.

Nevertheless, I'm wondering if it's exactly the expected behavior because
at the reinstall, I took off everything for the configuration.yaml, and I
had to add it again to have the intégration appearing.

Regards,
Guillaume Sourd

**Comment by josecarre** [comment]
> Had this issue, remove everything form the cofiguration yaml solved the issue

Fixed my notification issue, thanks! :)

**Comment by philder** [comment]
I solved the notification issue in my first post. I'm sorry if I wasn't clear enough. This is another problem: "Not getting entities".

I get this logs:

<img width="470" alt="Captura de ecrã 2022-09-20, às 12 34 12" src="https://user-images.githubusercontent.com/49433063/191247335-3f7f9691-ef15-4477-8fa0-06f666ada0b0.png">

`Este erro teve origem numa integração personalizada.

Logger: custom_components.securitas.securitas_direct_new_api.apimanager
Source: custom_components/securitas/securitas_direct_new_api/apimanager.py:297
Integration: Securitas Direct (documentation, issues)
First occurred: 12:31:19 (1 occurrences)
Last logged: 12:31:19

Unauthorized`

`Logger: homeassistant.helpers.service
Source: helpers/service.py:439
First occurred: 12:31:36 (1 occurrences)
Last logged: 12:31:36

Unable to find services.yaml for the securitas integration`

Thank you
