### ISSUE TITLE
No puedo crear script para perimetral

### ISSUE THREAD

**Issue by DJuanillo** [guerrerotook/securitas-direct-new-api#82]
Buenas, quiero crear un script para usar con google home, pero no me da la opción de crear un script para activar la zona perimetral, desde el panel de alarma lo puedo armar y desarmar, pero no me da la opción del script.
Un ejemplo de lo que si me deja hacer:

`'xxxxxxxxxxxxx':
  alias: Armar modo noche
  sequence:
  - device_id: xxxxxxxxxxxx
    domain: alarm_control_panel
    entity_id: alarm_control_panel.xxxxxxxx
    type: arm_night`

**Comment by DJuanillo** [comment]
Por cierto, Google home no me pide ningún código para poder desarmar la alarma, sin embargo, para abrir la puerta del garage si me pide el pin que tengo configurado, esto se puede implementar también? Gracias

**Comment by cantupaz** [comment]
esto debe estar resuelto en releases recientes
