### ISSUE TITLE
Unable to find services.yaml for the securitas integration

### ISSUE THREAD

**Issue by alnavasa** [guerrerotook/securitas-direct-new-api#83]
I get "_Unable to find services.yaml for the securitas integration_" error in the logs,
though **everything works perfectly** except for this error

````Logger: homeassistant.helpers.service
Source: helpers/service.py:439 
First occurred: 23:36:47 (1 occurrences) 
Last logged: 23:36:47

Unable to find services.yaml for the securitas integration

**Comment by guerrerotook** [comment]
Did you install the integration from the main branch?

**Comment by alnavasa** [comment]
> Did you install the integration from the main branch?

Installed via HACS, stable version, no beta versions neither nothing wired.
