### ISSUE TITLE
Si el PIN comienza con un cero, no funciona

### ISSUE THREAD

**Issue by mcamou** [guerrerotook/securitas-direct-new-api#86]
En una instalación donde el `code` comienza con un cero, lo he puesto entre comillas para que sea un String y use el cero inicial. `ha config check` me ha dado `Invalid config for [securitas]: expected int for dictionary value @ data['securitas']['code']`

Si lo pones como Int, se perderá el cero inicial.

Poniendo un `code` distinto (que no comience por cero) funciona y el componente arranca, pero no se puede bloquear ni desbloquear.

**Comment by guerrerotook** [comment]
Gracias por reportar, es porque se configuro el tipo de datos como entero y no como cadena de texto. Déjame que lo mire.

**Comment by guerrerotook** [comment]
Solucionado en este commit! 3bd89bcd3af2721c6c753aa8f06dd1230617b31a
