### ISSUE TITLE
Adding support for Sentinel sensors

### ISSUE THREAD

**Issue by jarredthejellyfish** [guerrerotook/securitas-direct-new-api#9]
Gooad day,

Firstly, thank you very much for all the work you have put into creating such a useful component / integration.

Is there any chance that support for the Verisure Sentinel _(the device that logs humidity, air quality, and temperature)_ could be added?

I am happy to provide captured responses from the API or anything you may need.
Attached is a screenshot that shows the device in question on the Verisure wesite.

Have a great rest of your day!

![Verisure - Sentinel](https://user-images.githubusercontent.com/50416421/147597116-80f455bb-032a-4713-b888-8777f758ad0d.png)

**Comment by jarredthejellyfish** [comment]
Fully forgot to add this.

Are there any plans to add support for taking pictures through the cameras in the installation?
If there are, I'm happy to be of service or help in any way I can.

**Comment by guerrerotook** [comment]
Hey @jarredthejellyfish that would be fantastic. Do you know how to capture the payloads to share with me?

**Comment by jarredthejellyfish** [comment]
@guerrerotook I'm not very familiar with it but I'm sure I can figure it out.
What exactly would you need so I can get started right now?

**Comment by guerrerotook** [comment]
I have the same panel with this information and I'm going to start creating a sensor. I will keep you posted.

**Comment by jarredthejellyfish** [comment]
Amazing, thank you!

**Comment by guerrerotook** [comment]
I have a working in progress sentinel support that adds two sensor for each sentinel.

<img width="401" alt="image" src="https://user-images.githubusercontent.com/769831/147757552-1a30473a-1d1a-46f5-a29d-b26f4425231f.png">

**Comment by jarredthejellyfish** [comment]
That's wonderful! 
Is one sensor the current value and the other the average over x period of time?
Thank you for your amazing work

**Comment by guerrerotook** [comment]
Sensors works by reading the value of the sentinel each 30 minutes and on top of that HA will create the graph and other stuff.
