### ISSUE TITLE
Ha dejado de funcionar

### ISSUE THREAD

**Issue by DJuanillo** [guerrerotook/securitas-direct-new-api#92]
Intento armar la alarma y no funciona:

`Este error se originó a partir de una integración personalizada.

Logger: custom_components.securitas.securitas_direct_new_api.apimanager
Source: custom_components/securitas/securitas_direct_new_api/apimanager.py:518
Integration: Securitas Direct (documentation, issues)
First occurred: 12:00:07 (3 occurrences)
Last logged: 12:02:14

Unknown argument "pin" on field "Mutation.xSArmPanel".`

**Comment by DJuanillo** [comment]
La versión de Home Assistant es la 2022.10.3

**Comment by soysnorre** [comment]
@DJuanillo estoy con el mismo error que comentas en la configuración, lo cual no me permite ni reiniciar HA  a no ser que comente la parte de Securitas en configuration.yaml.

Invalid config for [securitas]: expected str for dictionary value @ data['securitas']['code']. Got 5552. (See /config/configuration.yaml, line 31).

Se ha conseguido algún workarround o similar?.

Gracias y un saludo,

**Comment by DJuanillo** [comment]
> @DJuanillo estoy con el mismo error que comentas en la configuración, lo cual no me permite ni reiniciar HA a no ser que comente la parte de Securitas en configuration.yaml.
> 
> Invalid config for [securitas]: expected str for dictionary value @ data['securitas']['code']. Got 5552. (See /config/configuration.yaml, line 31).
> 
> Se ha conseguido algún workarround o similar?.
> 
> Gracias y un saludo,

El problema es que al comentar esa línea ya no deja desarmar la alarma, he intentado desinstalar y volver a instalar la integración varias veces y el problema persiste

**Comment by DJuanillo** [comment]
Nadie encuentra la solución?

**Comment by ursus69** [comment]
> 

De hecho el error lo dice, esta esperando un **string** en **code**,
Yo lo solucione poniendo single quotes antes y despues del **code** ex `'1234'` y luego funciona

**Comment by DJuanillo** [comment]
> > 
> 
> De hecho el error lo dice, esta esperando un **string** en **code**, Yo lo solucione poniendo single quotes antes y despues del **code** ex `'1234'` y luego funciona

Gracias, voy a probarlo.

**Comment by pedropaislopes** [comment]
Hola! Se me ocurrió el mismo error ahora que intenté desarmar. El error es `Unknown argument "pin" on field "Mutation.xSDisarmPanel".` No sé la razón pero no tengo problemas en armar. Toda mi configuración es por el ConfigFlow, no tengo nada en los archivos YAML.

Después de algún debug llegué a la conclusión que el upgrade del Home Assistant Core parece ser el culpable, porque manteniendo la integración en la versión `2.1.0.0` (la última), con el Core en la `2022.10.1`, funciona todo perfecto. Si hago el upgrade del core a la `2022.10.5` no funciona.

Con eso quedo un poco mas tranquilo que no es un problema con Securitas, Verisure o con mi cuenta, y si con el ecosistema del HA. Claro, la solución definitiva es corregir algo en la integración.

Para los que urge funcionar sugiero hacer el downgrade del Core.

**Comment by sergiomart96** [comment]
eliminar las líneas alarm_control_plane.py:311-316 y ya funciona

**Comment by DJuanillo** [comment]
> eliminar las líneas alarm_control_plane.py:311-316 y ya funciona

Funciona perfecto, gracias.
