### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by cosimomeli** [guerrerotook/securitas-direct-new-api#93]
Hi,
I get random Unauthorized for every call after some uptime. The issue is solved restarting HA.
The log is just `ERROR (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] Unauthorized`

Looks like a token is never refreshed and expires after some time.

**Comment by guerrerotook** [comment]
Did you try to remove and re add the integration again?
