### ISSUE TITLE
configuration.yaml validation error

### ISSUE THREAD

**Issue by luigixx73** [guerrerotook/securitas-direct-new-api#94]
In configuration.yaml

securitas:
  username: !secret securitas_direct_username
  password: !secret securitas_direct_password
  code: ---------> EXPECTED STRING VALUE
  country: ES

If you set a string value for code in configuration.yaml or secrets.yaml  and go to validation, HA will show an error as by code __init__.py  line # 66 is expecting a string.

It also affects to disarming function that doesn't work.
Replacing line #66 with:
vol.Optional(CONF_CODE, default=1234): int,

will define this parameter as integer so it will work for validation and disarming.

B.Regards!!

**Comment by guerrerotook** [comment]
Oh yes, this is because the internal state of HA had the configuration as integer, but I have to change it to int. You may need to remove the configuration, the integration and reinstall again. Sorry for the confusion but there was some users that has codes that starts with zeros.

**Comment by luigixx73** [comment]
Good job Luis, thanks
________________________________
De: Luis Guerrero ***@***.***>
Enviado: miércoles, 23 de noviembre de 2022 17:29
Para: guerrerotook/securitas-direct-new-api ***@***.***>
Cc: luigixx73 ***@***.***>; Author ***@***.***>
Asunto: Re: [guerrerotook/securitas-direct-new-api] configuration.yaml validation error (Issue #94)


Oh yes, this is because the internal state of HA had the configuration as integer, but I have to change it to int. You may need to remove the configuration, the integration and reinstall again. Sorry for the confusion but there was some users that has codes that starts with zeros.

**Comment by PozoSer** [comment]
I'm having the same issue. Just installed it and it expects a string.
