### ISSUE TITLE
New securitas-direct-new-api intergration Version 2.1.0.0 is not able to disarm from any armed state

### ISSUE THREAD

**Issue by Javvaz** [guerrerotook/securitas-direct-new-api#95]
Since yesterday Nov 8 the securitas-direct-new-api intergration version 2.1.0.0. is not able to disarm from any arm state.
When I try to disarm the alarm the below messages can be found in home-assitant.log with debug mode:

![image](https://user-images.githubusercontent.com/98023153/200928668-33f8f285-6550-4226-bb34-117e918d4302.png)

**Comment by bilbon0bud** [comment]
hello, the same issue here.

https://github.com/guerrerotook/securitas-direct-new-api/issues/90

Best Regards

**Comment by guerrerotook** [comment]
I have no idea why. Can you share the logs a little bit before to see what was the status of the alarm?

I'm interested in the request when disarming the alarm.

**Comment by Javvaz** [comment]
The below messages appear in home-assistant.log when I request to disarm the alarm from armed_custom_bypass (just perimetral armed), indeed it doesn't get it.

![image](https://user-images.githubusercontent.com/98023153/203602542-cb0cc5c4-31fe-42ce-9599-f0f6576db69d.png)

**Comment by Javvaz** [comment]
I forgot, I try to disarm the alarm in the control panel to simplify the log. In the scripts neither works.  From the any other status (armed_away, armed_home) it works disarming those status, but if the permitral is armed at the same time, then the final status is armed_custom_bypass (permitral armed), it is never able to disarm armed_custom_bypass.

**Comment by guerrerotook** [comment]
Solved in this release https://github.com/guerrerotook/securitas-direct-new-api/releases/tag/v2.1.0.0
