### ISSUE TITLE
configuration.yaml won't accept code

### ISSUE THREAD

**Issue by PozoSer** [guerrerotook/securitas-direct-new-api#98]
Same as #94. Supposedly it is fixed but the configuration.yaml won't allow me to introduce a numeric code (e.g. 1234) as it expects a string value. In my case the country is ES.

Thanks for the work!

**Comment by PozoSer** [comment]
My bad. You should configure the username, password and code on the devices/integrations page, not directly on the config.yaml file. All works properly.

**Comment by Tanjohnson99** [comment]
Same issue here. won't accept code

**Comment by guerrerotook** [comment]
configuration is not used anymore because of the support of config_flow. If you want to change your code, there is an special directory in the config folder, .storage. In there you can find core.config_entries and you can find the integration configuration, modify this there and restart.
